import { Component, OnInit } from '@angular/core';

@Component({
	selector: 'app-tiket-pesawat',
	templateUrl: './tiket-pesawat.component.html',
	styleUrls: ['./tiket-pesawat.component.scss'],
})
export class TiketPesawatComponent implements OnInit {
	columns: any[];
	data: any[] = [];
	constructor() {}

	ngOnInit(): void {
		this.columns = [
			{ field: 'createdAt', header: 'Tgl Order' },
			{ field: 'nameCompany', header: 'Company Name' },
			{ field: 'memberName', header: 'Member Name' },
			{ field: 'nik', header: 'NRP' },
			{ field: 'bookingReference', header: 'Book Ref' },
			{ field: 'owrAirlineName', header: 'Airline' },
			{ field: 'paymentTotal', header: 'Payment Amount' },
			{ field: 'flightType', header: 'Flight Type' },
			{ field: 'departureName', header: 'Departure' },
			{ field: 'arrivalName', header: 'Arrival' },
			{ field: 'owrDeparture', header: 'Tgl Berangkat' },
		];
		this.data = [
			{
				countData: 707,
				bookingReference: 'FMNID30YSZMK65',
				bookingStatus: 'Waiting to Payment',
				nik: null,
				memberName: null,
				nameCompany: null,
				paymentType: null,
				flightType: 'Sekali Jalan',
				isDomestic: true,
				owrAirlineIata: 'JT',
				owrAirlineName: 'Lion Air',
				retAirlineIata: null,
				retAirlineName: null,
				owrDeparture: '2021-09-11T07:30:00',
				retDeparture: null,
				departureCode: 'CGK',
				departureName: 'Bandar Udara Soekarno-Hatta - Cengkareng, Banten',
				arrivalCode: 'DPS',
				arrivalName: 'Bandar Udara Soekarno-Hatta - Cengkareng, Banten',
				details:
					'{"flight":[{"key":0,"carrier":{"code":"JT","name":"Lion Airways"},"operatingCarrier":null,"depDetail":{"city":"Jakarta","time":"2021-09-11T07:30:00","terminal":"2D","id_airport":0,"id_country":0,"country":"Indonesia","alpha_2_code":null,"alpha_3_code":null,"code":"CGK","name":"Jakarta-soekarno Hatta"},"arrDetail":{"city":"Bali/ Denpasar","time":"2021-09-11T10:20:00","terminal":"*","id_airport":0,"id_country":0,"country":"Indonesia","alpha_2_code":null,"alpha_3_code":null,"code":"DPS","name":"Bali/ Denpasar"},"flightNo":"28","classDetail":{"adt":{"class":"V","basis":""},"chd":{"class":"","basis":""},"inf":null},"aircraftType":null,"stops":0,"stopDetail":null,"flyTime":110,"layover":0,"isReturn":false,"amenities":{"baggage":{"checkin":{"adt":{"desc":"20 KG Included","qty":null,"unit":null,"code":null,"amount":0.0},"chd":{"desc":"20 KG Included","qty":null,"unit":null,"code":null,"amount":0.0},"inf":null},"cabin":{"adt":{"desc":"7 Kg ","qty":null,"unit":null,"code":null,"amount":0.0},"chd":{"desc":"7 Kg ","qty":null,"unit":null,"code":null,"amount":0.0},"inf":null}},"meal":false},"equipmentType":null,"nextDayArr":false,"onlyHandbag":false}], "fares":{"paxFares":{"adt":{"base":{"amount":426000.0,"decs":null},"tax":{"amount":132600.0,"decs":null},"total":{"amount":558600.0,"decs":null},"tcf":null,"bookFeeTax":null,"nta":{"amount":557820.0,"decs":null}},"chd":{"base":{"amount":426000.0,"decs":null},"tax":{"amount":132600.0,"decs":null},"total":{"amount":560080.0,"decs":null},"tcf":null,"bookFeeTax":null,"nta":{"amount":560080.0,"decs":null}},"inf":null},"totalFare":{"base":{"amount":1704000.0,"decs":null},"tax":{"amount":530400.0,"decs":null},"total":{"amount":2235880.0,"decs":null},"tcf":null,"bookFeeTax":null,"nta":{"amount":2233541.0,"decs":null}}}, "extraService":{"insurance":{"plans":[{"company":"ace","name":"Chubb Travel Insurance","code":"99_99_0.0_0","url":{"privacypolicy":"http://docs.chubbtravelinsurance.com/aceStatic/Doc/ID/Via/Via_privacy.pdf","tnc":"http://docs.chubbtravelinsurance.com/aceStatic/Doc/ID/Via/Via_policywording.pdf","declaration":"http://docs.chubbtravelinsurance.com/aceStatic/Doc/ID/Via/Via_declaration.pdf"},"amountPerPax":15000.0,"totalAmt":60000.0,"passportConditions":{"applicable":false},"discount":25714.285}]}}}',
				adt: 3,
				chd: 1,
				inf: 0,
				totalPassenger: 4,
				paymentTotal: 2235880,
				paymentStatus: 'Waiting for Payment',
				createdBy: 0,
				createdAt: '2021-09-09T06:23:18.097',
				updatedBy: 0,
				updatedAt: null,
				deletedBy: 0,
				deletedAt: null,
			},
			{
				countData: 707,
				bookingReference: 'FMNID30YSYIC3L',
				bookingStatus: 'Confirmed',
				nik: null,
				memberName: null,
				nameCompany: null,
				paymentType: null,
				flightType: 'Pulang Pergi',
				isDomestic: true,
				owrAirlineIata: 'JT',
				owrAirlineName: 'Lion Air',
				retAirlineIata: 'JT',
				retAirlineName: 'Lion Air',
				owrDeparture: '2021-09-10T04:00:00',
				retDeparture: '2021-09-10T09:25:00',
				departureCode: 'CGK',
				departureName: 'Bandar Udara Soekarno-Hatta - Cengkareng, Banten',
				arrivalCode: 'UPG',
				arrivalName: 'Bandar Udara Soekarno-Hatta - Cengkareng, Banten',
				details:
					'{"flight":[{"key":0,"carrier":{"code":"JT","name":"Lion Airways"},"operatingCarrier":null,"depDetail":{"city":"Jakarta","time":"2021-09-10T04:00:00","terminal":"2D","id_airport":0,"id_country":0,"country":"Indonesia","alpha_2_code":null,"alpha_3_code":null,"code":"CGK","name":"Jakarta-soekarno Hatta"},"arrDetail":{"city":"Makassar","time":"2021-09-10T07:25:00","terminal":"*","id_airport":0,"id_country":0,"country":"Indonesia","alpha_2_code":null,"alpha_3_code":null,"code":"UPG","name":"Makassar/ Ujung Pandang"},"flightNo":"898","classDetail":{"adt":{"class":"V","basis":""},"chd":null,"inf":null},"aircraftType":null,"stops":0,"stopDetail":null,"flyTime":145,"layover":120,"isReturn":false,"amenities":{"baggage":{"checkin":{"adt":{"desc":"20 KG Included","qty":null,"unit":null,"code":null,"amount":0.0},"chd":null,"inf":null},"cabin":{"adt":{"desc":"7 Kg ","qty":null,"unit":null,"code":null,"amount":0.0},"chd":null,"inf":null}},"meal":false},"equipmentType":null,"nextDayArr":false,"onlyHandbag":false},{"key":1,"carrier":{"code":"JT","name":"Lion Airways"},"operatingCarrier":null,"depDetail":{"city":"Makassar","time":"2021-09-10T09:25:00","terminal":null,"id_airport":0,"id_country":0,"country":"Indonesia","alpha_2_code":null,"alpha_3_code":null,"code":"UPG","name":"Makassar/ Ujung Pandang"},"arrDetail":{"city":"Bali/ Denpasar","time":"2021-09-10T10:50:00","terminal":null,"id_airport":0,"id_country":0,"country":"Indonesia","alpha_2_code":null,"alpha_3_code":null,"code":"DPS","name":"Bali/ Denpasar"},"flightNo":"741","classDetail":{"adt":{"class":"Q","basis":""},"chd":null,"inf":null},"aircraftType":null,"stops":0,"stopDetail":null,"flyTime":85,"layover":0,"isReturn":false,"amenities":{"baggage":{"checkin":{"adt":{"desc":"20 KG Included","qty":null,"unit":null,"code":null,"amount":0.0},"chd":null,"inf":null},"cabin":{"adt":{"desc":"7 Kg ","qty":null,"unit":null,"code":null,"amount":0.0},"chd":null,"inf":null}},"meal":false},"equipmentType":null,"nextDayArr":false,"onlyHandbag":false},{"key":2,"carrier":{"code":"JT","name":"Lion Airways"},"operatingCarrier":null,"depDetail":{"city":"Bali/ Denpasar","time":"2021-09-10T11:00:00","terminal":"*","id_airport":0,"id_country":0,"country":"Indonesia","alpha_2_code":null,"alpha_3_code":null,"code":"DPS","name":"Bali/ Denpasar"},"arrDetail":{"city":"Jakarta","time":"2021-09-10T11:50:00","terminal":"2D","id_airport":0,"id_country":0,"country":"Indonesia","alpha_2_code":null,"alpha_3_code":null,"code":"CGK","name":"Jakarta-soekarno Hatta"},"flightNo":"29","classDetail":{"adt":{"class":"V","basis":""},"chd":null,"inf":null},"aircraftType":null,"stops":0,"stopDetail":null,"flyTime":110,"layover":0,"isReturn":true,"amenities":{"baggage":{"checkin":{"adt":{"desc":"20 KG Included","qty":null,"unit":null,"code":null,"amount":0.0},"chd":null,"inf":null},"cabin":{"adt":{"desc":"7 Kg ","qty":null,"unit":null,"code":null,"amount":0.0},"chd":null,"inf":null}},"meal":false},"equipmentType":null,"nextDayArr":false,"onlyHandbag":false}], "fares":{"paxFares":{"adt":{"base":{"amount":1419000.0,"decs":null},"tax":{"amount":341900.0,"decs":null},"total":{"amount":1770900.0,"decs":null},"tcf":null,"bookFeeTax":null,"nta":{"amount":1745215.0,"decs":null}},"chd":null,"inf":null},"totalFare":{"base":{"amount":1419000.0,"decs":null},"tax":{"amount":341900.0,"decs":null},"total":{"amount":1770900.0,"decs":null},"tcf":null,"bookFeeTax":null,"nta":{"amount":1745215.0,"decs":null}}}, "extraService":{"insurance":{"plans":[{"company":"ace","name":"Chubb Travel Insurance","code":"99_99_0.0_0","url":{"privacypolicy":"http://docs.chubbtravelinsurance.com/aceStatic/Doc/ID/Via/Via_privacy.pdf","tnc":"http://docs.chubbtravelinsurance.com/aceStatic/Doc/ID/Via/Via_policywording.pdf","declaration":"http://docs.chubbtravelinsurance.com/aceStatic/Doc/ID/Via/Via_declaration.pdf"},"amountPerPax":30000.0,"totalAmt":30000.0,"passportConditions":{"applicable":false},"discount":12857.143}]}}}',
				adt: 1,
				chd: 0,
				inf: 0,
				totalPassenger: 1,
				paymentTotal: 1770900,
				paymentStatus: '',
				createdBy: 0,
				createdAt: '2021-09-09T03:02:28.98',
				updatedBy: 0,
				updatedAt: '2021-09-09T03:02:51.753',
				deletedBy: 0,
				deletedAt: null,
			},
			{
				countData: 707,
				bookingReference: 'FMNID30YSX7Y1D',
				bookingStatus: 'Confirmed',
				nik: null,
				memberName: null,
				nameCompany: null,
				paymentType: null,
				flightType: 'Pulang Pergi',
				isDomestic: true,
				owrAirlineIata: 'ID',
				owrAirlineName: null,
				retAirlineIata: 'JT',
				retAirlineName: 'Lion Air',
				owrDeparture: '2021-09-10T06:10:00',
				retDeparture: '2021-09-10T09:50:00',
				departureCode: 'CGK',
				departureName: 'Bandar Udara Soekarno-Hatta - Cengkareng, Banten',
				arrivalCode: 'LOP',
				arrivalName: 'Bandar Udara Soekarno-Hatta - Cengkareng, Banten',
				details:
					'{"flight":[{"key":0,"carrier":{"code":"ID","name":"Batik Air"},"operatingCarrier":null,"depDetail":{"city":"Jakarta","time":"2021-09-10T06:10:00","terminal":"2E","id_airport":0,"id_country":0,"country":"Indonesia","alpha_2_code":null,"alpha_3_code":null,"code":"CGK","name":"Jakarta-soekarno Hatta"},"arrDetail":{"city":"Lombok","time":"2021-09-10T09:10:00","terminal":null,"id_airport":0,"id_country":0,"country":"Indonesia","alpha_2_code":null,"alpha_3_code":null,"code":"LOP","name":"Lombok/ Mataram"},"flightNo":"6656","classDetail":{"adt":{"class":"L","basis":""},"chd":null,"inf":null},"aircraftType":null,"stops":0,"stopDetail":null,"flyTime":120,"layover":40,"isReturn":false,"amenities":{"baggage":{"checkin":{"adt":{"desc":"20 KG","qty":null,"unit":null,"code":null,"amount":0.0},"chd":null,"inf":null},"cabin":{"adt":{"desc":"7 Kg ","qty":null,"unit":null,"code":null,"amount":0.0},"chd":null,"inf":null}},"meal":false},"equipmentType":null,"nextDayArr":false,"onlyHandbag":false},{"key":1,"carrier":{"code":"JT","name":"Lion Airways"},"operatingCarrier":null,"depDetail":{"city":"Lombok","time":"2021-09-10T09:50:00","terminal":null,"id_airport":0,"id_country":0,"country":"Indonesia","alpha_2_code":null,"alpha_3_code":null,"code":"LOP","name":"Lombok/ Mataram"},"arrDetail":{"city":"Bali/ Denpasar","time":"2021-09-10T10:30:00","terminal":null,"id_airport":0,"id_country":0,"country":"Indonesia","alpha_2_code":null,"alpha_3_code":null,"code":"DPS","name":"Bali/ Denpasar"},"flightNo":"955","classDetail":{"adt":{"class":"Q","basis":""},"chd":null,"inf":null},"aircraftType":null,"stops":0,"stopDetail":null,"flyTime":40,"layover":0,"isReturn":false,"amenities":{"baggage":{"checkin":{"adt":{"desc":"20 KG Included","qty":null,"unit":null,"code":null,"amount":0.0},"chd":null,"inf":null},"cabin":{"adt":{"desc":"7 Kg ","qty":null,"unit":null,"code":null,"amount":0.0},"chd":null,"inf":null}},"meal":false},"equipmentType":null,"nextDayArr":false,"onlyHandbag":false},{"key":2,"carrier":{"code":"JT","name":"Lion Airways"},"operatingCarrier":null,"depDetail":{"city":"Bali/ Denpasar","time":"2021-09-13T10:00:00","terminal":"*","id_airport":0,"id_country":0,"country":"Indonesia","alpha_2_code":null,"alpha_3_code":null,"code":"DPS","name":"Bali/ Denpasar"},"arrDetail":{"city":"Jakarta","time":"2021-09-13T10:55:00","terminal":"2D","id_airport":0,"id_country":0,"country":"Indonesia","alpha_2_code":null,"alpha_3_code":null,"code":"CGK","name":"Jakarta-soekarno Hatta"},"flightNo":"11","classDetail":{"adt":{"class":"V","basis":""},"chd":null,"inf":null},"aircraftType":null,"stops":0,"stopDetail":null,"flyTime":115,"layover":0,"isReturn":true,"amenities":{"baggage":{"checkin":{"adt":{"desc":"20 KG Included","qty":null,"unit":null,"code":null,"amount":0.0},"chd":null,"inf":null},"cabin":{"adt":{"desc":"7 Kg ","qty":null,"unit":null,"code":null,"amount":0.0},"chd":null,"inf":null}},"meal":false},"equipmentType":null,"nextDayArr":false,"onlyHandbag":false}], "fares":{"paxFares":{"adt":{"base":{"amount":1387000.0,"decs":null},"tax":{"amount":338700.0,"decs":null},"total":{"amount":1735700.0,"decs":null},"tcf":null,"bookFeeTax":null,"nta":{"amount":1707119.0,"decs":null}},"chd":null,"inf":null},"totalFare":{"base":{"amount":1387000.0,"decs":null},"tax":{"amount":338700.0,"decs":null},"total":{"amount":1735700.0,"decs":null},"tcf":null,"bookFeeTax":null,"nta":{"amount":1707119.0,"decs":null}}}, "extraService":{"insurance":{"plans":[{"company":"ace","name":"Chubb Travel Insurance","code":"99_99_0.0_0","url":{"privacypolicy":"http://docs.chubbtravelinsurance.com/aceStatic/Doc/ID/Via/Via_privacy.pdf","tnc":"http://docs.chubbtravelinsurance.com/aceStatic/Doc/ID/Via/Via_policywording.pdf","declaration":"http://docs.chubbtravelinsurance.com/aceStatic/Doc/ID/Via/Via_declaration.pdf"},"amountPerPax":30000.0,"totalAmt":30000.0,"passportConditions":{"applicable":false},"discount":12857.143}]}}}',
				adt: 1,
				chd: 0,
				inf: 0,
				totalPassenger: 1,
				paymentTotal: 1735700,
				paymentStatus: '',
				createdBy: 0,
				createdAt: '2021-09-08T17:25:49.313',
				updatedBy: 0,
				updatedAt: '2021-09-08T17:26:03.18',
				deletedBy: 0,
				deletedAt: null,
			},
			{
				countData: 707,
				bookingReference: 'FMNID30YRZSVU6',
				bookingStatus: 'Waiting to Payment',
				nik: null,
				memberName: null,
				nameCompany: null,
				paymentType: null,
				flightType: 'Pulang Pergi',
				isDomestic: true,
				owrAirlineIata: 'ID',
				owrAirlineName: null,
				retAirlineIata: 'QG',
				retAirlineName: null,
				owrDeparture: '2021-09-02T12:00:00',
				retDeparture: '2021-09-02T17:35:00',
				departureCode: 'HLP',
				departureName: 'Bandar Udara Halim Perdanakusuma - Jakarta',
				arrivalCode: 'SUB',
				arrivalName: 'Bandar Udara Halim Perdanakusuma - Jakarta',
				details:
					'{"flight":[{"key":0,"carrier":{"code":"ID","name":"Batik Air"},"operatingCarrier":null,"depDetail":{"city":"Jakarta","time":"2021-09-02T12:00:00","terminal":null,"id_airport":0,"id_country":0,"country":"Indonesia","alpha_2_code":null,"alpha_3_code":null,"code":"HLP","name":"Jakarta-halim"},"arrDetail":{"city":"Surabaya","time":"2021-09-02T13:30:00","terminal":null,"id_airport":0,"id_country":0,"country":"Indonesia","alpha_2_code":null,"alpha_3_code":null,"code":"SUB","name":"Surabaya"},"flightNo":"7513","classDetail":{"adt":{"class":"M","basis":""},"chd":null,"inf":null},"aircraftType":null,"stops":0,"stopDetail":null,"flyTime":90,"layover":0,"isReturn":false,"amenities":{"baggage":{"checkin":{"adt":{"desc":"20 KG","qty":null,"unit":null,"code":null,"amount":0.0},"chd":null,"inf":null},"cabin":{"adt":{"desc":"7 Kg ","qty":null,"unit":null,"code":null,"amount":0.0},"chd":null,"inf":null}},"meal":false},"equipmentType":null,"nextDayArr":false,"onlyHandbag":false},{"key":1,"carrier":{"code":"QG","name":"Citilink"},"operatingCarrier":null,"depDetail":{"city":"Surabaya","time":"2021-09-02T17:35:00","terminal":"1","id_airport":0,"id_country":0,"country":"Indonesia","alpha_2_code":null,"alpha_3_code":null,"code":"SUB","name":"Surabaya"},"arrDetail":{"city":"Jakarta","time":"2021-09-02T19:05:00","terminal":"3 Domestic","id_airport":0,"id_country":0,"country":"Indonesia","alpha_2_code":null,"alpha_3_code":null,"code":"CGK","name":"Jakarta-soekarno Hatta"},"flightNo":"737","classDetail":{"adt":{"class":"OTN","basis":"OTN"},"chd":null,"inf":null},"aircraftType":"Airbus A320","stops":0,"stopDetail":null,"flyTime":90,"layover":0,"isReturn":true,"amenities":{"baggage":{"checkin":{"adt":{"desc":"20 Kg Included","qty":null,"unit":null,"code":null,"amount":0.0},"chd":null,"inf":null},"cabin":{"adt":{"desc":"7 Kg ","qty":null,"unit":null,"code":null,"amount":0.0},"chd":null,"inf":null}},"meal":false},"equipmentType":null,"nextDayArr":false,"onlyHandbag":false}], "fares":{"paxFares":{"adt":{"base":{"amount":1136000.0,"decs":null},"tax":{"amount":289600.0,"decs":null},"total":{"amount":1430680.0,"decs":null},"tcf":null,"bookFeeTax":null,"nta":{"amount":1422426.0,"decs":null}},"chd":null,"inf":null},"totalFare":{"base":{"amount":1136000.0,"decs":null},"tax":{"amount":289600.0,"decs":null},"total":{"amount":1430680.0,"decs":null},"tcf":null,"bookFeeTax":null,"nta":{"amount":1422426.0,"decs":null}}}, "extraService":{"insurance":{"plans":[{"company":"ace","name":"Chubb Travel Insurance","code":"99_99_0.0_0","url":{"privacypolicy":"http://docs.chubbtravelinsurance.com/aceStatic/Doc/ID/Via/Via_privacy.pdf","tnc":"http://docs.chubbtravelinsurance.com/aceStatic/Doc/ID/Via/Via_policywording.pdf","declaration":"http://docs.chubbtravelinsurance.com/aceStatic/Doc/ID/Via/Via_declaration.pdf"},"amountPerPax":30000.0,"totalAmt":30000.0,"passportConditions":{"applicable":false},"discount":12857.143}]}}}',
				adt: 1,
				chd: 0,
				inf: 0,
				totalPassenger: 1,
				paymentTotal: 1430680,
				paymentStatus: 'Waiting for Payment',
				createdBy: 0,
				createdAt: '2021-09-01T17:52:23.827',
				updatedBy: 0,
				updatedAt: null,
				deletedBy: 0,
				deletedAt: null,
			},
			{
				countData: 707,
				bookingReference: 'FMNID30YRZSTIK',
				bookingStatus: 'Waiting to Payment',
				nik: null,
				memberName: null,
				nameCompany: null,
				paymentType: null,
				flightType: 'Pulang Pergi',
				isDomestic: true,
				owrAirlineIata: 'ID',
				owrAirlineName: null,
				retAirlineIata: 'QG',
				retAirlineName: null,
				owrDeparture: '2021-09-02T12:00:00',
				retDeparture: '2021-09-02T17:35:00',
				departureCode: 'HLP',
				departureName: 'Bandar Udara Halim Perdanakusuma - Jakarta',
				arrivalCode: 'SUB',
				arrivalName: 'Bandar Udara Halim Perdanakusuma - Jakarta',
				details:
					'{"flight":[{"key":0,"carrier":{"code":"ID","name":"Batik Air"},"operatingCarrier":null,"depDetail":{"city":"Jakarta","time":"2021-09-02T12:00:00","terminal":null,"id_airport":0,"id_country":0,"country":"Indonesia","alpha_2_code":null,"alpha_3_code":null,"code":"HLP","name":"Jakarta-halim"},"arrDetail":{"city":"Surabaya","time":"2021-09-02T13:30:00","terminal":null,"id_airport":0,"id_country":0,"country":"Indonesia","alpha_2_code":null,"alpha_3_code":null,"code":"SUB","name":"Surabaya"},"flightNo":"7513","classDetail":{"adt":{"class":"M","basis":""},"chd":null,"inf":null},"aircraftType":null,"stops":0,"stopDetail":null,"flyTime":90,"layover":0,"isReturn":false,"amenities":{"baggage":{"checkin":{"adt":{"desc":"20 KG","qty":null,"unit":null,"code":null,"amount":0.0},"chd":null,"inf":null},"cabin":{"adt":{"desc":"7 Kg ","qty":null,"unit":null,"code":null,"amount":0.0},"chd":null,"inf":null}},"meal":false},"equipmentType":null,"nextDayArr":false,"onlyHandbag":false},{"key":1,"carrier":{"code":"QG","name":"Citilink"},"operatingCarrier":null,"depDetail":{"city":"Surabaya","time":"2021-09-02T17:35:00","terminal":"1","id_airport":0,"id_country":0,"country":"Indonesia","alpha_2_code":null,"alpha_3_code":null,"code":"SUB","name":"Surabaya"},"arrDetail":{"city":"Jakarta","time":"2021-09-02T19:05:00","terminal":"3 Domestic","id_airport":0,"id_country":0,"country":"Indonesia","alpha_2_code":null,"alpha_3_code":null,"code":"CGK","name":"Jakarta-soekarno Hatta"},"flightNo":"737","classDetail":{"adt":{"class":"OTN","basis":"OTN"},"chd":null,"inf":null},"aircraftType":"Airbus A320","stops":0,"stopDetail":null,"flyTime":90,"layover":0,"isReturn":true,"amenities":{"baggage":{"checkin":{"adt":{"desc":"20 Kg Included","qty":null,"unit":null,"code":null,"amount":0.0},"chd":null,"inf":null},"cabin":{"adt":{"desc":"7 Kg ","qty":null,"unit":null,"code":null,"amount":0.0},"chd":null,"inf":null}},"meal":false},"equipmentType":null,"nextDayArr":false,"onlyHandbag":false}], "fares":{"paxFares":{"adt":{"base":{"amount":1136000.0,"decs":null},"tax":{"amount":289600.0,"decs":null},"total":{"amount":1430680.0,"decs":null},"tcf":null,"bookFeeTax":null,"nta":{"amount":1422426.0,"decs":null}},"chd":null,"inf":null},"totalFare":{"base":{"amount":1136000.0,"decs":null},"tax":{"amount":289600.0,"decs":null},"total":{"amount":1430680.0,"decs":null},"tcf":null,"bookFeeTax":null,"nta":{"amount":1422426.0,"decs":null}}}, "extraService":{"insurance":{"plans":[{"company":"ace","name":"Chubb Travel Insurance","code":"99_99_0.0_0","url":{"privacypolicy":"http://docs.chubbtravelinsurance.com/aceStatic/Doc/ID/Via/Via_privacy.pdf","tnc":"http://docs.chubbtravelinsurance.com/aceStatic/Doc/ID/Via/Via_policywording.pdf","declaration":"http://docs.chubbtravelinsurance.com/aceStatic/Doc/ID/Via/Via_declaration.pdf"},"amountPerPax":30000.0,"totalAmt":30000.0,"passportConditions":{"applicable":false},"discount":12857.143}]}}}',
				adt: 1,
				chd: 0,
				inf: 0,
				totalPassenger: 1,
				paymentTotal: 1430680,
				paymentStatus: 'Waiting for Payment',
				createdBy: 0,
				createdAt: '2021-09-01T17:52:19.333',
				updatedBy: 0,
				updatedAt: null,
				deletedBy: 0,
				deletedAt: null,
			},
			{
				countData: 707,
				bookingReference: 'FMNID30YRZSKH4',
				bookingStatus: 'Confirmed',
				nik: null,
				memberName: null,
				nameCompany: null,
				paymentType: null,
				flightType: 'Pulang Pergi',
				isDomestic: true,
				owrAirlineIata: 'ID',
				owrAirlineName: null,
				retAirlineIata: 'QG',
				retAirlineName: null,
				owrDeparture: '2021-09-02T12:00:00',
				retDeparture: '2021-09-02T17:35:00',
				departureCode: 'HLP',
				departureName: 'Bandar Udara Halim Perdanakusuma - Jakarta',
				arrivalCode: 'SUB',
				arrivalName: 'Bandar Udara Halim Perdanakusuma - Jakarta',
				details:
					'{"flight":[{"key":0,"carrier":{"code":"ID","name":"Batik Air"},"operatingCarrier":null,"depDetail":{"city":"Jakarta","time":"2021-09-02T12:00:00","terminal":null,"id_airport":0,"id_country":0,"country":"Indonesia","alpha_2_code":null,"alpha_3_code":null,"code":"HLP","name":"Jakarta-halim"},"arrDetail":{"city":"Surabaya","time":"2021-09-02T13:30:00","terminal":null,"id_airport":0,"id_country":0,"country":"Indonesia","alpha_2_code":null,"alpha_3_code":null,"code":"SUB","name":"Surabaya"},"flightNo":"7513","classDetail":{"adt":{"class":"M","basis":""},"chd":null,"inf":null},"aircraftType":null,"stops":0,"stopDetail":null,"flyTime":90,"layover":0,"isReturn":false,"amenities":{"baggage":{"checkin":{"adt":{"desc":"20 KG","qty":null,"unit":null,"code":null,"amount":0.0},"chd":null,"inf":null},"cabin":{"adt":{"desc":"7 Kg ","qty":null,"unit":null,"code":null,"amount":0.0},"chd":null,"inf":null}},"meal":false},"equipmentType":null,"nextDayArr":false,"onlyHandbag":false},{"key":1,"carrier":{"code":"QG","name":"Citilink"},"operatingCarrier":null,"depDetail":{"city":"Surabaya","time":"2021-09-02T17:35:00","terminal":"1","id_airport":0,"id_country":0,"country":"Indonesia","alpha_2_code":null,"alpha_3_code":null,"code":"SUB","name":"Surabaya"},"arrDetail":{"city":"Jakarta","time":"2021-09-02T19:05:00","terminal":"3 Domestic","id_airport":0,"id_country":0,"country":"Indonesia","alpha_2_code":null,"alpha_3_code":null,"code":"CGK","name":"Jakarta-soekarno Hatta"},"flightNo":"737","classDetail":{"adt":{"class":"OTN","basis":"OTN"},"chd":null,"inf":null},"aircraftType":"Airbus A320","stops":0,"stopDetail":null,"flyTime":90,"layover":0,"isReturn":true,"amenities":{"baggage":{"checkin":{"adt":{"desc":"20 Kg Included","qty":null,"unit":null,"code":null,"amount":0.0},"chd":null,"inf":null},"cabin":{"adt":{"desc":"7 Kg ","qty":null,"unit":null,"code":null,"amount":0.0},"chd":null,"inf":null}},"meal":false},"equipmentType":null,"nextDayArr":false,"onlyHandbag":false}], "fares":{"paxFares":{"adt":{"base":{"amount":1136000.0,"decs":null},"tax":{"amount":289600.0,"decs":null},"total":{"amount":1430680.0,"decs":null},"tcf":null,"bookFeeTax":null,"nta":{"amount":1422426.0,"decs":null}},"chd":null,"inf":null},"totalFare":{"base":{"amount":1136000.0,"decs":null},"tax":{"amount":289600.0,"decs":null},"total":{"amount":1430680.0,"decs":null},"tcf":null,"bookFeeTax":null,"nta":{"amount":1422426.0,"decs":null}}}, "extraService":{"insurance":{"plans":[{"company":"ace","name":"Chubb Travel Insurance","code":"99_99_0.0_0","url":{"privacypolicy":"http://docs.chubbtravelinsurance.com/aceStatic/Doc/ID/Via/Via_privacy.pdf","tnc":"http://docs.chubbtravelinsurance.com/aceStatic/Doc/ID/Via/Via_policywording.pdf","declaration":"http://docs.chubbtravelinsurance.com/aceStatic/Doc/ID/Via/Via_declaration.pdf"},"amountPerPax":30000.0,"totalAmt":30000.0,"passportConditions":{"applicable":false},"discount":12857.143}]}}}',
				adt: 1,
				chd: 0,
				inf: 0,
				totalPassenger: 1,
				paymentTotal: 1430680,
				paymentStatus: '',
				createdBy: 0,
				createdAt: '2021-09-01T17:50:56.583',
				updatedBy: 0,
				updatedAt: '2021-09-01T17:51:08.063',
				deletedBy: 0,
				deletedAt: null,
			},
			{
				countData: 707,
				bookingReference: 'FMNID30YRZSBUM',
				bookingStatus: 'Waiting to Payment',
				nik: null,
				memberName: null,
				nameCompany: null,
				paymentType: null,
				flightType: 'Pulang Pergi',
				isDomestic: true,
				owrAirlineIata: 'JT',
				owrAirlineName: 'Lion Air',
				retAirlineIata: 'ID',
				retAirlineName: null,
				owrDeparture: '2021-09-02T07:00:00',
				retDeparture: '2021-09-02T14:10:00',
				departureCode: 'CGK',
				departureName: 'Bandar Udara Soekarno-Hatta - Cengkareng, Banten',
				arrivalCode: 'SUB',
				arrivalName: 'Bandar Udara Soekarno-Hatta - Cengkareng, Banten',
				details:
					'{"flight":[{"key":0,"carrier":{"code":"JT","name":"Lion Airways"},"operatingCarrier":null,"depDetail":{"city":"Jakarta","time":"2021-09-02T07:00:00","terminal":"2D","id_airport":0,"id_country":0,"country":"Indonesia","alpha_2_code":null,"alpha_3_code":null,"code":"CGK","name":"Jakarta-soekarno Hatta"},"arrDetail":{"city":"Surabaya","time":"2021-09-02T08:30:00","terminal":"1","id_airport":0,"id_country":0,"country":"Indonesia","alpha_2_code":null,"alpha_3_code":null,"code":"SUB","name":"Surabaya"},"flightNo":"692","classDetail":{"adt":{"class":"T","basis":""},"chd":null,"inf":null},"aircraftType":null,"stops":0,"stopDetail":null,"flyTime":90,"layover":0,"isReturn":false,"amenities":{"baggage":{"checkin":{"adt":{"desc":"20 KG Included","qty":null,"unit":null,"code":null,"amount":0.0},"chd":null,"inf":null},"cabin":{"adt":{"desc":"7 Kg ","qty":null,"unit":null,"code":null,"amount":0.0},"chd":null,"inf":null}},"meal":false},"equipmentType":null,"nextDayArr":false,"onlyHandbag":false},{"key":1,"carrier":{"code":"ID","name":"Batik Air"},"operatingCarrier":null,"depDetail":{"city":"Surabaya","time":"2021-09-02T14:10:00","terminal":null,"id_airport":0,"id_country":0,"country":"Indonesia","alpha_2_code":null,"alpha_3_code":null,"code":"SUB","name":"Surabaya"},"arrDetail":{"city":"Jakarta","time":"2021-09-02T15:40:00","terminal":null,"id_airport":0,"id_country":0,"country":"Indonesia","alpha_2_code":null,"alpha_3_code":null,"code":"HLP","name":"Jakarta-halim"},"flightNo":"7512","classDetail":{"adt":{"class":"T","basis":""},"chd":null,"inf":null},"aircraftType":null,"stops":0,"stopDetail":null,"flyTime":90,"layover":0,"isReturn":true,"amenities":{"baggage":{"checkin":{"adt":{"desc":"20 KG","qty":null,"unit":null,"code":null,"amount":0.0},"chd":null,"inf":null},"cabin":{"adt":{"desc":"7 Kg ","qty":null,"unit":null,"code":null,"amount":0.0},"chd":null,"inf":null}},"meal":false},"equipmentType":null,"nextDayArr":false,"onlyHandbag":false}], "fares":{"paxFares":{"adt":{"base":{"amount":861000.0,"decs":null},"tax":{"amount":282100.0,"decs":null},"total":{"amount":1153100.0,"decs":null},"tcf":null,"bookFeeTax":null,"nta":{"amount":1139860.0,"decs":null}},"chd":null,"inf":null},"totalFare":{"base":{"amount":861000.0,"decs":null},"tax":{"amount":282100.0,"decs":null},"total":{"amount":1153100.0,"decs":null},"tcf":null,"bookFeeTax":null,"nta":{"amount":1139860.0,"decs":null}}}, "extraService":{"insurance":{"plans":[{"company":"ace","name":"Chubb Travel Insurance","code":"99_99_0.0_0","url":{"privacypolicy":"http://docs.chubbtravelinsurance.com/aceStatic/Doc/ID/Via/Via_privacy.pdf","tnc":"http://docs.chubbtravelinsurance.com/aceStatic/Doc/ID/Via/Via_policywording.pdf","declaration":"http://docs.chubbtravelinsurance.com/aceStatic/Doc/ID/Via/Via_declaration.pdf"},"amountPerPax":30000.0,"totalAmt":30000.0,"passportConditions":{"applicable":false},"discount":12857.143}]}}}',
				adt: 1,
				chd: 0,
				inf: 0,
				totalPassenger: 1,
				paymentTotal: 1153100,
				paymentStatus: 'Waiting for Payment',
				createdBy: 0,
				createdAt: '2021-09-01T17:50:03.973',
				updatedBy: 0,
				updatedAt: null,
				deletedBy: 0,
				deletedAt: null,
			},
			{
				countData: 707,
				bookingReference: 'FMNID30YRZQOAL',
				bookingStatus: 'Confirmed',
				nik: null,
				memberName: null,
				nameCompany: null,
				paymentType: null,
				flightType: 'Pulang Pergi',
				isDomestic: true,
				owrAirlineIata: 'QG',
				owrAirlineName: null,
				retAirlineIata: 'QG',
				retAirlineName: null,
				owrDeparture: '2021-09-02T05:30:00',
				retDeparture: '2021-09-02T17:35:00',
				departureCode: 'CGK',
				departureName: 'Bandar Udara Soekarno-Hatta - Cengkareng, Banten',
				arrivalCode: 'SUB',
				arrivalName: 'Bandar Udara Soekarno-Hatta - Cengkareng, Banten',
				details:
					'{"flight":[{"key":0,"carrier":{"code":"QG","name":"Citilink"},"operatingCarrier":null,"depDetail":{"city":"Jakarta","time":"2021-09-02T05:30:00","terminal":"3 Domestic","id_airport":0,"id_country":0,"country":"Indonesia","alpha_2_code":null,"alpha_3_code":null,"code":"CGK","name":"Jakarta-soekarno Hatta"},"arrDetail":{"city":"Surabaya","time":"2021-09-02T07:00:00","terminal":"1","id_airport":0,"id_country":0,"country":"Indonesia","alpha_2_code":null,"alpha_3_code":null,"code":"SUB","name":"Surabaya"},"flightNo":"714","classDetail":{"adt":{"class":"OTN","basis":"OTN"},"chd":null,"inf":null},"aircraftType":"Airbus A320","stops":0,"stopDetail":null,"flyTime":90,"layover":0,"isReturn":false,"amenities":{"baggage":{"checkin":{"adt":{"desc":"20 Kg Included","qty":null,"unit":null,"code":null,"amount":0.0},"chd":null,"inf":null},"cabin":{"adt":{"desc":"7 Kg ","qty":null,"unit":null,"code":null,"amount":0.0},"chd":null,"inf":null}},"meal":false},"equipmentType":null,"nextDayArr":false,"onlyHandbag":false},{"key":1,"carrier":{"code":"QG","name":"Citilink"},"operatingCarrier":null,"depDetail":{"city":"Surabaya","time":"2021-09-02T17:35:00","terminal":"1","id_airport":0,"id_country":0,"country":"Indonesia","alpha_2_code":null,"alpha_3_code":null,"code":"SUB","name":"Surabaya"},"arrDetail":{"city":"Jakarta","time":"2021-09-02T19:05:00","terminal":"3 Domestic","id_airport":0,"id_country":0,"country":"Indonesia","alpha_2_code":null,"alpha_3_code":null,"code":"CGK","name":"Jakarta-soekarno Hatta"},"flightNo":"737","classDetail":{"adt":{"class":"OTN","basis":"OTN"},"chd":null,"inf":null},"aircraftType":"Airbus A320","stops":0,"stopDetail":null,"flyTime":90,"layover":0,"isReturn":true,"amenities":{"baggage":{"checkin":{"adt":{"desc":"20 Kg Included","qty":null,"unit":null,"code":null,"amount":0.0},"chd":null,"inf":null},"cabin":{"adt":{"desc":"7 Kg ","qty":null,"unit":null,"code":null,"amount":0.0},"chd":null,"inf":null}},"meal":false},"equipmentType":null,"nextDayArr":false,"onlyHandbag":false}], "fares":{"paxFares":{"adt":{"base":{"amount":992000.0,"decs":null},"tax":{"amount":285200.0,"decs":null},"total":{"amount":1287360.0,"decs":null},"tcf":null,"bookFeeTax":null,"nta":{"amount":1287360.0,"decs":null}},"chd":null,"inf":null},"totalFare":{"base":{"amount":992000.0,"decs":null},"tax":{"amount":285200.0,"decs":null},"total":{"amount":1287360.0,"decs":null},"tcf":null,"bookFeeTax":null,"nta":{"amount":1287360.0,"decs":null}}}, "extraService":{"insurance":{"plans":[{"company":"ace","name":"Chubb Travel Insurance","code":"99_99_0.0_0","url":{"privacypolicy":"http://docs.chubbtravelinsurance.com/aceStatic/Doc/ID/Via/Via_privacy.pdf","tnc":"http://docs.chubbtravelinsurance.com/aceStatic/Doc/ID/Via/Via_policywording.pdf","declaration":"http://docs.chubbtravelinsurance.com/aceStatic/Doc/ID/Via/Via_declaration.pdf"},"amountPerPax":30000.0,"totalAmt":30000.0,"passportConditions":{"applicable":false},"discount":12857.143}]}}}',
				adt: 1,
				chd: 0,
				inf: 0,
				totalPassenger: 1,
				paymentTotal: 1287360,
				paymentStatus: '',
				createdBy: 0,
				createdAt: '2021-09-01T17:42:56.55',
				updatedBy: 0,
				updatedAt: '2021-09-01T17:43:02.173',
				deletedBy: 0,
				deletedAt: null,
			},
			{
				countData: 707,
				bookingReference: 'FMNID30YRZPB49',
				bookingStatus: 'Confirmed',
				nik: null,
				memberName: null,
				nameCompany: null,
				paymentType: null,
				flightType: 'Pulang Pergi',
				isDomestic: true,
				owrAirlineIata: 'JT',
				owrAirlineName: 'Lion Air',
				retAirlineIata: 'QG',
				retAirlineName: null,
				owrDeparture: '2021-09-03T07:00:00',
				retDeparture: '2021-09-03T12:40:00',
				departureCode: 'CGK',
				departureName: 'Bandar Udara Soekarno-Hatta - Cengkareng, Banten',
				arrivalCode: 'SUB',
				arrivalName: 'Bandar Udara Soekarno-Hatta - Cengkareng, Banten',
				details:
					'{"flight":[{"key":0,"carrier":{"code":"JT","name":"Lion Airways"},"operatingCarrier":null,"depDetail":{"city":"Jakarta","time":"2021-09-03T07:00:00","terminal":"2D","id_airport":0,"id_country":0,"country":"Indonesia","alpha_2_code":null,"alpha_3_code":null,"code":"CGK","name":"Jakarta-soekarno Hatta"},"arrDetail":{"city":"Surabaya","time":"2021-09-03T08:30:00","terminal":"1","id_airport":0,"id_country":0,"country":"Indonesia","alpha_2_code":null,"alpha_3_code":null,"code":"SUB","name":"Surabaya"},"flightNo":"692","classDetail":{"adt":{"class":"V","basis":""},"chd":null,"inf":null},"aircraftType":null,"stops":0,"stopDetail":null,"flyTime":90,"layover":0,"isReturn":false,"amenities":{"baggage":{"checkin":{"adt":{"desc":"20 KG Included","qty":null,"unit":null,"code":null,"amount":0.0},"chd":null,"inf":null},"cabin":{"adt":{"desc":"7 Kg ","qty":null,"unit":null,"code":null,"amount":0.0},"chd":null,"inf":null}},"meal":false},"equipmentType":null,"nextDayArr":false,"onlyHandbag":false},{"key":1,"carrier":{"code":"QG","name":"Citilink"},"operatingCarrier":null,"depDetail":{"city":"Surabaya","time":"2021-09-03T12:40:00","terminal":"1","id_airport":0,"id_country":0,"country":"Indonesia","alpha_2_code":null,"alpha_3_code":null,"code":"SUB","name":"Surabaya"},"arrDetail":{"city":"Jakarta","time":"2021-09-03T14:10:00","terminal":"3 Domestic","id_airport":0,"id_country":0,"country":"Indonesia","alpha_2_code":null,"alpha_3_code":null,"code":"CGK","name":"Jakarta-soekarno Hatta"},"flightNo":"717","classDetail":{"adt":{"class":"OTN","basis":"OTN"},"chd":null,"inf":null},"aircraftType":"Airbus A320","stops":0,"stopDetail":null,"flyTime":90,"layover":0,"isReturn":true,"amenities":{"baggage":{"checkin":{"adt":{"desc":"20 Kg Included","qty":null,"unit":null,"code":null,"amount":0.0},"chd":null,"inf":null},"cabin":{"adt":{"desc":"7 Kg ","qty":null,"unit":null,"code":null,"amount":0.0},"chd":null,"inf":null}},"meal":false},"equipmentType":null,"nextDayArr":false,"onlyHandbag":false}], "fares":{"paxFares":{"adt":{"base":{"amount":844000.0,"decs":null},"tax":{"amount":275400.0,"decs":null},"total":{"amount":1126545.0,"decs":null},"tcf":null,"bookFeeTax":null,"nta":{"amount":1126545.0,"decs":null}},"chd":null,"inf":null},"totalFare":{"base":{"amount":844000.0,"decs":null},"tax":{"amount":275400.0,"decs":null},"total":{"amount":1126545.0,"decs":null},"tcf":null,"bookFeeTax":null,"nta":{"amount":1126545.0,"decs":null}}}, "extraService":{"insurance":{"plans":[{"company":"ace","name":"Chubb Travel Insurance","code":"99_99_0.0_0","url":{"privacypolicy":"http://docs.chubbtravelinsurance.com/aceStatic/Doc/ID/Via/Via_privacy.pdf","tnc":"http://docs.chubbtravelinsurance.com/aceStatic/Doc/ID/Via/Via_policywording.pdf","declaration":"http://docs.chubbtravelinsurance.com/aceStatic/Doc/ID/Via/Via_declaration.pdf"},"amountPerPax":30000.0,"totalAmt":30000.0,"passportConditions":{"applicable":false},"discount":12857.143}]}}}',
				adt: 1,
				chd: 0,
				inf: 0,
				totalPassenger: 1,
				paymentTotal: 1126545,
				paymentStatus: '',
				createdBy: 0,
				createdAt: '2021-09-01T17:32:30.163',
				updatedBy: 0,
				updatedAt: '2021-09-01T17:36:52.633',
				deletedBy: 0,
				deletedAt: null,
			},
			{
				countData: 707,
				bookingReference: 'FMNID30YRZJRKT',
				bookingStatus: 'Waiting to Payment',
				nik: null,
				memberName: null,
				nameCompany: null,
				paymentType: null,
				flightType: 'Pulang Pergi',
				isDomestic: true,
				owrAirlineIata: 'JT',
				owrAirlineName: 'Lion Air',
				retAirlineIata: 'JT',
				retAirlineName: 'Lion Air',
				owrDeparture: '2021-09-15T04:50:00',
				retDeparture: '2021-09-30T11:00:00',
				departureCode: 'CGK',
				departureName: 'Bandar Udara Soekarno-Hatta - Cengkareng, Banten',
				arrivalCode: 'SUB',
				arrivalName: 'Bandar Udara Soekarno-Hatta - Cengkareng, Banten',
				details:
					'{"flight":[{"key":0,"carrier":{"code":"JT","name":"Lion Airways"},"operatingCarrier":null,"depDetail":{"city":"Jakarta","time":"2021-09-15T04:50:00","terminal":"2D","id_airport":0,"id_country":0,"country":"Indonesia","alpha_2_code":null,"alpha_3_code":null,"code":"CGK","name":"Jakarta-soekarno Hatta"},"arrDetail":{"city":"Surabaya","time":"2021-09-15T06:20:00","terminal":"1","id_airport":0,"id_country":0,"country":"Indonesia","alpha_2_code":null,"alpha_3_code":null,"code":"SUB","name":"Surabaya"},"flightNo":"690","classDetail":{"adt":{"class":"V","basis":""},"chd":null,"inf":null},"aircraftType":null,"stops":0,"stopDetail":null,"flyTime":90,"layover":0,"isReturn":false,"amenities":{"baggage":{"checkin":{"adt":{"desc":"20 KG Included","qty":null,"unit":null,"code":null,"amount":0.0},"chd":null,"inf":null},"cabin":{"adt":{"desc":"7 Kg ","qty":null,"unit":null,"code":null,"amount":0.0},"chd":null,"inf":null}},"meal":false},"equipmentType":null,"nextDayArr":false,"onlyHandbag":false},{"key":1,"carrier":{"code":"JT","name":"Lion Airways"},"operatingCarrier":null,"depDetail":{"city":"Surabaya","time":"2021-09-30T11:00:00","terminal":"1","id_airport":0,"id_country":0,"country":"Indonesia","alpha_2_code":null,"alpha_3_code":null,"code":"SUB","name":"Surabaya"},"arrDetail":{"city":"Jakarta","time":"2021-09-30T12:30:00","terminal":"2D","id_airport":0,"id_country":0,"country":"Indonesia","alpha_2_code":null,"alpha_3_code":null,"code":"CGK","name":"Jakarta-soekarno Hatta"},"flightNo":"591","classDetail":{"adt":{"class":"V","basis":""},"chd":null,"inf":null},"aircraftType":null,"stops":0,"stopDetail":null,"flyTime":90,"layover":0,"isReturn":true,"amenities":{"baggage":{"checkin":{"adt":{"desc":"20 KG Included","qty":null,"unit":null,"code":null,"amount":0.0},"chd":null,"inf":null},"cabin":{"adt":{"desc":"7 Kg ","qty":null,"unit":null,"code":null,"amount":0.0},"chd":null,"inf":null}},"meal":false},"equipmentType":null,"nextDayArr":false,"onlyHandbag":false}], "fares":{"paxFares":{"adt":{"base":{"amount":696000.0,"decs":null},"tax":{"amount":265600.0,"decs":null},"total":{"amount":971600.0,"decs":null},"tcf":null,"bookFeeTax":null,"nta":{"amount":966024.0,"decs":null}},"chd":null,"inf":null},"totalFare":{"base":{"amount":696000.0,"decs":null},"tax":{"amount":265600.0,"decs":null},"total":{"amount":971600.0,"decs":null},"tcf":null,"bookFeeTax":null,"nta":{"amount":966024.0,"decs":null}}}, "extraService":{"insurance":{"plans":[{"company":"ace","name":"Chubb Travel Insurance","code":"99_99_0.0_0","url":{"privacypolicy":"http://docs.chubbtravelinsurance.com/aceStatic/Doc/ID/Via/Via_privacy.pdf","tnc":"http://docs.chubbtravelinsurance.com/aceStatic/Doc/ID/Via/Via_policywording.pdf","declaration":"http://docs.chubbtravelinsurance.com/aceStatic/Doc/ID/Via/Via_declaration.pdf"},"amountPerPax":30000.0,"totalAmt":30000.0,"passportConditions":{"applicable":false},"discount":12857.143}]}}}',
				adt: 1,
				chd: 0,
				inf: 0,
				totalPassenger: 1,
				paymentTotal: 971600,
				paymentStatus: 'Waiting for Payment',
				createdBy: 0,
				createdAt: '2021-09-01T16:53:20.82',
				updatedBy: 0,
				updatedAt: null,
				deletedBy: 0,
				deletedAt: null,
			},
		];
	}
}
