import { Component, OnInit } from '@angular/core';

@Component({
	selector: 'app-tipe-pinjaman',
	templateUrl: './tipe-pinjaman.component.html',
	styleUrls: ['./tipe-pinjaman.component.scss'],
})
export class TipePinjamanComponent implements OnInit {
	displayForm: boolean = false;
	data: any[] = [];
	columns: any[];
	isShow: boolean = false;
	dataGolongan: any[];
	constructor() {}

	ngOnInit(): void {
		this.columns = [{ field: 'name_loan_type', header: 'Tipe Pinjaman' }];
		this.data = [
			{
				id_loan_type: '1214',
				name_loan_type: 'RPB 2020',
				icon_loan_type: '',
				min_plafond: 3048103.0,
				default_term: 9,
				interest: [
					{
						id_master_loan_interest: 149,
						id_loan_type: '1214',
						name_loan_type: 'RPB 2020',
						id_grade: 'GRD004',
						name_grade: 'IV',
						interest: 5.0,
					},
					{
						id_master_loan_interest: 150,
						id_loan_type: '1214',
						name_loan_type: 'RPB 2020',
						id_grade: 'GRD005',
						name_grade: 'V',
						interest: 5.0,
					},
					{
						id_master_loan_interest: 151,
						id_loan_type: '1214',
						name_loan_type: 'RPB 2020',
						id_grade: 'GRD006',
						name_grade: 'VI',
						interest: 5.0,
					},
					{
						id_master_loan_interest: 152,
						id_loan_type: '1214',
						name_loan_type: 'RPB 2020',
						id_grade: 'GRD001',
						name_grade: 'I',
						interest: 5.0,
					},
					{
						id_master_loan_interest: 153,
						id_loan_type: '1214',
						name_loan_type: 'RPB 2020',
						id_grade: 'GRD002',
						name_grade: 'II',
						interest: 5.0,
					},
					{
						id_master_loan_interest: 154,
						id_loan_type: '1214',
						name_loan_type: 'RPB 2020',
						id_grade: 'GRD003',
						name_grade: 'III',
						interest: 5.0,
					},
				],
				plafond: [
					{
						id_master_loan_plafond: 166,
						id_grade: 'GRD004',
						name_grade: 'IV',
						id_loan_type: '1214',
						name_loan_type: 'RPB 2020',
						loan_plafond: 150000000,
					},
					{
						id_master_loan_plafond: 167,
						id_grade: 'GRD005',
						name_grade: 'V',
						id_loan_type: '1214',
						name_loan_type: 'RPB 2020',
						loan_plafond: 150000000,
					},
					{
						id_master_loan_plafond: 168,
						id_grade: 'GRD006',
						name_grade: 'VI',
						id_loan_type: '1214',
						name_loan_type: 'RPB 2020',
						loan_plafond: 150000000,
					},
					{
						id_master_loan_plafond: 169,
						id_grade: 'GRD001',
						name_grade: 'I',
						id_loan_type: '1214',
						name_loan_type: 'RPB 2020',
						loan_plafond: 150000000,
					},
					{
						id_master_loan_plafond: 170,
						id_grade: 'GRD002',
						name_grade: 'II',
						id_loan_type: '1214',
						name_loan_type: 'RPB 2020',
						loan_plafond: 150000000,
					},
					{
						id_master_loan_plafond: 171,
						id_grade: 'GRD003',
						name_grade: 'III',
						id_loan_type: '1214',
						name_loan_type: 'RPB 2020',
						loan_plafond: 150000000,
					},
				],
			},
			{
				id_loan_type: 'LOAN0001',
				name_loan_type: 'Multiguna',
				icon_loan_type: 'https://lendtickdev.blob.core.windows.net/images/menu/loan/multiguna.jpg',
				min_plafond: 3048103.0,
				default_term: 9,
				interest: [
					{
						id_master_loan_interest: 4,
						id_loan_type: 'LOAN0001',
						name_loan_type: 'Multiguna',
						id_grade: 'GRD004',
						name_grade: 'IV',
						interest: 12.0,
					},
					{
						id_master_loan_interest: 5,
						id_loan_type: 'LOAN0001',
						name_loan_type: 'Multiguna',
						id_grade: 'GRD005',
						name_grade: 'V',
						interest: 12.0,
					},
					{
						id_master_loan_interest: 6,
						id_loan_type: 'LOAN0001',
						name_loan_type: 'Multiguna',
						id_grade: 'GRD006',
						name_grade: 'VI',
						interest: 12.0,
					},
					{
						id_master_loan_interest: 7,
						id_loan_type: 'LOAN0001',
						name_loan_type: 'Multiguna',
						id_grade: 'GRD007',
						name_grade: 'VII',
						interest: 12.0,
					},
					{
						id_master_loan_interest: 158,
						id_loan_type: 'LOAN0001',
						name_loan_type: 'Multiguna',
						id_grade: 'GRD001',
						name_grade: 'I',
						interest: 12.0,
					},
					{
						id_master_loan_interest: 159,
						id_loan_type: 'LOAN0001',
						name_loan_type: 'Multiguna',
						id_grade: 'GRD002',
						name_grade: 'II',
						interest: 12.0,
					},
					{
						id_master_loan_interest: 160,
						id_loan_type: 'LOAN0001',
						name_loan_type: 'Multiguna',
						id_grade: 'GRD003',
						name_grade: 'III',
						interest: 12.0,
					},
				],
				plafond: [
					{
						id_master_loan_plafond: 107,
						id_grade: 'GRD004',
						name_grade: 'IV',
						id_loan_type: 'LOAN0001',
						name_loan_type: 'Multiguna',
						loan_plafond: 100000000,
					},
					{
						id_master_loan_plafond: 121,
						id_grade: 'GRD005',
						name_grade: 'V',
						id_loan_type: 'LOAN0001',
						name_loan_type: 'Multiguna',
						loan_plafond: 200000000,
					},
					{
						id_master_loan_plafond: 135,
						id_grade: 'GRD006',
						name_grade: 'VI',
						id_loan_type: 'LOAN0001',
						name_loan_type: 'Multiguna',
						loan_plafond: 200000000,
					},
					{
						id_master_loan_plafond: 149,
						id_grade: 'GRD007',
						name_grade: 'VII',
						id_loan_type: 'LOAN0001',
						name_loan_type: 'Multiguna',
						loan_plafond: 200000000,
					},
					{
						id_master_loan_plafond: 175,
						id_grade: 'GRD001',
						name_grade: 'I',
						id_loan_type: 'LOAN0001',
						name_loan_type: 'Multiguna',
						loan_plafond: 50000000,
					},
					{
						id_master_loan_plafond: 176,
						id_grade: 'GRD002',
						name_grade: 'II',
						id_loan_type: 'LOAN0001',
						name_loan_type: 'Multiguna',
						loan_plafond: 50000000,
					},
					{
						id_master_loan_plafond: 177,
						id_grade: 'GRD003',
						name_grade: 'III',
						id_loan_type: 'LOAN0001',
						name_loan_type: 'Multiguna',
						loan_plafond: 50000000,
					},
				],
			},
			{
				id_loan_type: 'LOAN0002',
				name_loan_type: 'Program Device SF DSO',
				icon_loan_type: 'https://lendtickdev.blob.core.windows.net/images/menu/loan/middle_loan.jpg',
				min_plafond: 3048103.0,
				default_term: 9,
				interest: [
					{
						id_master_loan_interest: 54,
						id_loan_type: 'LOAN0002',
						name_loan_type: 'Program Device SF DSO',
						id_grade: 'GRD001',
						name_grade: 'I',
						interest: 8.5,
					},
					{
						id_master_loan_interest: 55,
						id_loan_type: 'LOAN0002',
						name_loan_type: 'Program Device SF DSO',
						id_grade: 'GRD002',
						name_grade: 'II',
						interest: 8.5,
					},
					{
						id_master_loan_interest: 56,
						id_loan_type: 'LOAN0002',
						name_loan_type: 'Program Device SF DSO',
						id_grade: 'GRD003',
						name_grade: 'III',
						interest: 8.5,
					},
					{
						id_master_loan_interest: 57,
						id_loan_type: 'LOAN0002',
						name_loan_type: 'Program Device SF DSO',
						id_grade: 'GRD004',
						name_grade: 'IV',
						interest: 9.0,
					},
					{
						id_master_loan_interest: 58,
						id_loan_type: 'LOAN0002',
						name_loan_type: 'Program Device SF DSO',
						id_grade: 'GRD005',
						name_grade: 'V',
						interest: 9.0,
					},
					{
						id_master_loan_interest: 59,
						id_loan_type: 'LOAN0002',
						name_loan_type: 'Program Device SF DSO',
						id_grade: 'GRD006',
						name_grade: 'VI',
						interest: 9.0,
					},
					{
						id_master_loan_interest: 60,
						id_loan_type: 'LOAN0002',
						name_loan_type: 'Program Device SF DSO',
						id_grade: 'GRD007',
						name_grade: 'VII',
						interest: 9.0,
					},
				],
				plafond: [
					{
						id_master_loan_plafond: 66,
						id_grade: 'GRD001',
						name_grade: 'I',
						id_loan_type: 'LOAN0002',
						name_loan_type: 'Program Device SF DSO',
						loan_plafond: 3000000,
					},
					{
						id_master_loan_plafond: 80,
						id_grade: 'GRD002',
						name_grade: 'II',
						id_loan_type: 'LOAN0002',
						name_loan_type: 'Program Device SF DSO',
						loan_plafond: 3000000,
					},
					{
						id_master_loan_plafond: 94,
						id_grade: 'GRD003',
						name_grade: 'III',
						id_loan_type: 'LOAN0002',
						name_loan_type: 'Program Device SF DSO',
						loan_plafond: 3000000,
					},
					{
						id_master_loan_plafond: 108,
						id_grade: 'GRD004',
						name_grade: 'IV',
						id_loan_type: 'LOAN0002',
						name_loan_type: 'Program Device SF DSO',
						loan_plafond: 3000000,
					},
					{
						id_master_loan_plafond: 122,
						id_grade: 'GRD005',
						name_grade: 'V',
						id_loan_type: 'LOAN0002',
						name_loan_type: 'Program Device SF DSO',
						loan_plafond: 3000000,
					},
					{
						id_master_loan_plafond: 136,
						id_grade: 'GRD006',
						name_grade: 'VI',
						id_loan_type: 'LOAN0002',
						name_loan_type: 'Program Device SF DSO',
						loan_plafond: 3000000,
					},
					{
						id_master_loan_plafond: 150,
						id_grade: 'GRD007',
						name_grade: 'VII',
						id_loan_type: 'LOAN0002',
						name_loan_type: 'Program Device SF DSO',
						loan_plafond: 3000000,
					},
				],
			},
			{
				id_loan_type: 'LOAN0003',
				name_loan_type: 'Priority',
				icon_loan_type: '',
				min_plafond: 3048103.0,
				default_term: 9,
				interest: [
					{
						id_master_loan_interest: 61,
						id_loan_type: 'LOAN0003',
						name_loan_type: 'Priority',
						id_grade: 'GRD001',
						name_grade: 'I',
						interest: 5.0,
					},
					{
						id_master_loan_interest: 62,
						id_loan_type: 'LOAN0003',
						name_loan_type: 'Priority',
						id_grade: 'GRD002',
						name_grade: 'II',
						interest: 5.0,
					},
					{
						id_master_loan_interest: 64,
						id_loan_type: 'LOAN0003',
						name_loan_type: 'Priority',
						id_grade: 'GRD004',
						name_grade: 'IV',
						interest: 5.0,
					},
					{
						id_master_loan_interest: 65,
						id_loan_type: 'LOAN0003',
						name_loan_type: 'Priority',
						id_grade: 'GRD005',
						name_grade: 'V',
						interest: 5.0,
					},
					{
						id_master_loan_interest: 66,
						id_loan_type: 'LOAN0003',
						name_loan_type: 'Priority',
						id_grade: 'GRD006',
						name_grade: 'VI',
						interest: 5.0,
					},
					{
						id_master_loan_interest: 67,
						id_loan_type: 'LOAN0003',
						name_loan_type: 'Priority',
						id_grade: 'GRD007',
						name_grade: 'VII',
						interest: 5.0,
					},
					{
						id_master_loan_interest: 145,
						id_loan_type: 'LOAN0003',
						name_loan_type: 'Priority',
						id_grade: 'GRD003',
						name_grade: 'III',
						interest: 5.0,
					},
				],
				plafond: [
					{
						id_master_loan_plafond: 67,
						id_grade: 'GRD001',
						name_grade: 'I',
						id_loan_type: 'LOAN0003',
						name_loan_type: 'Priority',
						loan_plafond: 100000000,
					},
					{
						id_master_loan_plafond: 81,
						id_grade: 'GRD002',
						name_grade: 'II',
						id_loan_type: 'LOAN0003',
						name_loan_type: 'Priority',
						loan_plafond: 100000000,
					},
					{
						id_master_loan_plafond: 95,
						id_grade: 'GRD003',
						name_grade: 'III',
						id_loan_type: 'LOAN0003',
						name_loan_type: 'Priority',
						loan_plafond: 75000000,
					},
					{
						id_master_loan_plafond: 109,
						id_grade: 'GRD004',
						name_grade: 'IV',
						id_loan_type: 'LOAN0003',
						name_loan_type: 'Priority',
						loan_plafond: 100000000,
					},
					{
						id_master_loan_plafond: 123,
						id_grade: 'GRD005',
						name_grade: 'V',
						id_loan_type: 'LOAN0003',
						name_loan_type: 'Priority',
						loan_plafond: 100000000,
					},
					{
						id_master_loan_plafond: 137,
						id_grade: 'GRD006',
						name_grade: 'VI',
						id_loan_type: 'LOAN0003',
						name_loan_type: 'Priority',
						loan_plafond: 100000000,
					},
					{
						id_master_loan_plafond: 151,
						id_grade: 'GRD007',
						name_grade: 'VII',
						id_loan_type: 'LOAN0003',
						name_loan_type: 'Priority',
						loan_plafond: 100000000,
					},
				],
			},
			{
				id_loan_type: 'LOAN0004',
				name_loan_type: 'Fleksi',
				icon_loan_type: '',
				min_plafond: 3048103.0,
				default_term: 9,
				interest: [
					{
						id_master_loan_interest: 71,
						id_loan_type: 'LOAN0004',
						name_loan_type: 'Fleksi',
						id_grade: 'GRD004',
						name_grade: 'IV',
						interest: 8.5,
					},
					{
						id_master_loan_interest: 72,
						id_loan_type: 'LOAN0004',
						name_loan_type: 'Fleksi',
						id_grade: 'GRD005',
						name_grade: 'V',
						interest: 8.5,
					},
					{
						id_master_loan_interest: 73,
						id_loan_type: 'LOAN0004',
						name_loan_type: 'Fleksi',
						id_grade: 'GRD006',
						name_grade: 'VI',
						interest: 8.5,
					},
					{
						id_master_loan_interest: 74,
						id_loan_type: 'LOAN0004',
						name_loan_type: 'Fleksi',
						id_grade: 'GRD007',
						name_grade: 'VII',
						interest: 8.5,
					},
					{
						id_master_loan_interest: 155,
						id_loan_type: 'LOAN0004',
						name_loan_type: 'Fleksi',
						id_grade: 'GRD001',
						name_grade: 'I',
						interest: 8.5,
					},
					{
						id_master_loan_interest: 156,
						id_loan_type: 'LOAN0004',
						name_loan_type: 'Fleksi',
						id_grade: 'GRD002',
						name_grade: 'II',
						interest: 8.5,
					},
					{
						id_master_loan_interest: 157,
						id_loan_type: 'LOAN0004',
						name_loan_type: 'Fleksi',
						id_grade: 'GRD003',
						name_grade: 'III',
						interest: 8.5,
					},
				],
				plafond: [
					{
						id_master_loan_plafond: 110,
						id_grade: 'GRD004',
						name_grade: 'IV',
						id_loan_type: 'LOAN0004',
						name_loan_type: 'Fleksi',
						loan_plafond: 100000000,
					},
					{
						id_master_loan_plafond: 124,
						id_grade: 'GRD005',
						name_grade: 'V',
						id_loan_type: 'LOAN0004',
						name_loan_type: 'Fleksi',
						loan_plafond: 100000000,
					},
					{
						id_master_loan_plafond: 138,
						id_grade: 'GRD006',
						name_grade: 'VI',
						id_loan_type: 'LOAN0004',
						name_loan_type: 'Fleksi',
						loan_plafond: 100000000,
					},
					{
						id_master_loan_plafond: 152,
						id_grade: 'GRD007',
						name_grade: 'VII',
						id_loan_type: 'LOAN0004',
						name_loan_type: 'Fleksi',
						loan_plafond: 100000000,
					},
					{
						id_master_loan_plafond: 172,
						id_grade: 'GRD001',
						name_grade: 'I',
						id_loan_type: 'LOAN0004',
						name_loan_type: 'Fleksi',
						loan_plafond: 100000000,
					},
					{
						id_master_loan_plafond: 173,
						id_grade: 'GRD002',
						name_grade: 'II',
						id_loan_type: 'LOAN0004',
						name_loan_type: 'Fleksi',
						loan_plafond: 100000000,
					},
					{
						id_master_loan_plafond: 174,
						id_grade: 'GRD003',
						name_grade: 'III',
						id_loan_type: 'LOAN0004',
						name_loan_type: 'Fleksi',
						loan_plafond: 100000000,
					},
				],
			},
			{
				id_loan_type: 'LOAN0005',
				name_loan_type: 'Modal Usaha Pensiun',
				icon_loan_type: '',
				min_plafond: 3048103.0,
				default_term: 9,
				interest: [
					{
						id_master_loan_interest: 75,
						id_loan_type: 'LOAN0005',
						name_loan_type: 'Modal Usaha Pensiun',
						id_grade: 'GRD001',
						name_grade: 'I',
						interest: 7.0,
					},
					{
						id_master_loan_interest: 76,
						id_loan_type: 'LOAN0005',
						name_loan_type: 'Modal Usaha Pensiun',
						id_grade: 'GRD002',
						name_grade: 'II',
						interest: 7.0,
					},
					{
						id_master_loan_interest: 77,
						id_loan_type: 'LOAN0005',
						name_loan_type: 'Modal Usaha Pensiun',
						id_grade: 'GRD003',
						name_grade: 'III',
						interest: 7.0,
					},
					{
						id_master_loan_interest: 78,
						id_loan_type: 'LOAN0005',
						name_loan_type: 'Modal Usaha Pensiun',
						id_grade: 'GRD004',
						name_grade: 'IV',
						interest: 7.5,
					},
					{
						id_master_loan_interest: 79,
						id_loan_type: 'LOAN0005',
						name_loan_type: 'Modal Usaha Pensiun',
						id_grade: 'GRD005',
						name_grade: 'V',
						interest: 7.5,
					},
					{
						id_master_loan_interest: 80,
						id_loan_type: 'LOAN0005',
						name_loan_type: 'Modal Usaha Pensiun',
						id_grade: 'GRD006',
						name_grade: 'VI',
						interest: 7.5,
					},
					{
						id_master_loan_interest: 81,
						id_loan_type: 'LOAN0005',
						name_loan_type: 'Modal Usaha Pensiun',
						id_grade: 'GRD007',
						name_grade: 'VII',
						interest: 7.5,
					},
				],
				plafond: [
					{
						id_master_loan_plafond: 69,
						id_grade: 'GRD001',
						name_grade: 'I',
						id_loan_type: 'LOAN0005',
						name_loan_type: 'Modal Usaha Pensiun',
						loan_plafond: 25000000,
					},
					{
						id_master_loan_plafond: 83,
						id_grade: 'GRD002',
						name_grade: 'II',
						id_loan_type: 'LOAN0005',
						name_loan_type: 'Modal Usaha Pensiun',
						loan_plafond: 25000000,
					},
					{
						id_master_loan_plafond: 97,
						id_grade: 'GRD003',
						name_grade: 'III',
						id_loan_type: 'LOAN0005',
						name_loan_type: 'Modal Usaha Pensiun',
						loan_plafond: 25000000,
					},
					{
						id_master_loan_plafond: 111,
						id_grade: 'GRD004',
						name_grade: 'IV',
						id_loan_type: 'LOAN0005',
						name_loan_type: 'Modal Usaha Pensiun',
						loan_plafond: 50000000,
					},
					{
						id_master_loan_plafond: 125,
						id_grade: 'GRD005',
						name_grade: 'V',
						id_loan_type: 'LOAN0005',
						name_loan_type: 'Modal Usaha Pensiun',
						loan_plafond: 50000000,
					},
					{
						id_master_loan_plafond: 139,
						id_grade: 'GRD006',
						name_grade: 'VI',
						id_loan_type: 'LOAN0005',
						name_loan_type: 'Modal Usaha Pensiun',
						loan_plafond: 50000000,
					},
					{
						id_master_loan_plafond: 153,
						id_grade: 'GRD007',
						name_grade: 'VII',
						id_loan_type: 'LOAN0005',
						name_loan_type: 'Modal Usaha Pensiun',
						loan_plafond: 50000000,
					},
				],
			},
			{
				id_loan_type: 'LOAN0006',
				name_loan_type: 'Sewa Rumah',
				icon_loan_type: '',
				min_plafond: 3048103.0,
				default_term: 9,
				interest: [
					{
						id_master_loan_interest: 82,
						id_loan_type: 'LOAN0006',
						name_loan_type: 'Sewa Rumah',
						id_grade: 'GRD001',
						name_grade: 'I',
						interest: 4.5,
					},
					{
						id_master_loan_interest: 83,
						id_loan_type: 'LOAN0006',
						name_loan_type: 'Sewa Rumah',
						id_grade: 'GRD002',
						name_grade: 'II',
						interest: 4.5,
					},
					{
						id_master_loan_interest: 84,
						id_loan_type: 'LOAN0006',
						name_loan_type: 'Sewa Rumah',
						id_grade: 'GRD003',
						name_grade: 'III',
						interest: 4.5,
					},
					{
						id_master_loan_interest: 85,
						id_loan_type: 'LOAN0006',
						name_loan_type: 'Sewa Rumah',
						id_grade: 'GRD004',
						name_grade: 'IV',
						interest: 5.0,
					},
					{
						id_master_loan_interest: 86,
						id_loan_type: 'LOAN0006',
						name_loan_type: 'Sewa Rumah',
						id_grade: 'GRD005',
						name_grade: 'V',
						interest: 5.0,
					},
					{
						id_master_loan_interest: 87,
						id_loan_type: 'LOAN0006',
						name_loan_type: 'Sewa Rumah',
						id_grade: 'GRD006',
						name_grade: 'VI',
						interest: 5.0,
					},
					{
						id_master_loan_interest: 88,
						id_loan_type: 'LOAN0006',
						name_loan_type: 'Sewa Rumah',
						id_grade: 'GRD007',
						name_grade: 'VII',
						interest: 5.0,
					},
				],
				plafond: [
					{
						id_master_loan_plafond: 70,
						id_grade: 'GRD001',
						name_grade: 'I',
						id_loan_type: 'LOAN0006',
						name_loan_type: 'Sewa Rumah',
						loan_plafond: 10000000,
					},
					{
						id_master_loan_plafond: 84,
						id_grade: 'GRD002',
						name_grade: 'II',
						id_loan_type: 'LOAN0006',
						name_loan_type: 'Sewa Rumah',
						loan_plafond: 10000000,
					},
					{
						id_master_loan_plafond: 98,
						id_grade: 'GRD003',
						name_grade: 'III',
						id_loan_type: 'LOAN0006',
						name_loan_type: 'Sewa Rumah',
						loan_plafond: 10000000,
					},
					{
						id_master_loan_plafond: 112,
						id_grade: 'GRD004',
						name_grade: 'IV',
						id_loan_type: 'LOAN0006',
						name_loan_type: 'Sewa Rumah',
						loan_plafond: 15000000,
					},
					{
						id_master_loan_plafond: 126,
						id_grade: 'GRD005',
						name_grade: 'V',
						id_loan_type: 'LOAN0006',
						name_loan_type: 'Sewa Rumah',
						loan_plafond: 15000000,
					},
					{
						id_master_loan_plafond: 140,
						id_grade: 'GRD006',
						name_grade: 'VI',
						id_loan_type: 'LOAN0006',
						name_loan_type: 'Sewa Rumah',
						loan_plafond: 15000000,
					},
					{
						id_master_loan_plafond: 154,
						id_grade: 'GRD007',
						name_grade: 'VII',
						id_loan_type: 'LOAN0006',
						name_loan_type: 'Sewa Rumah',
						loan_plafond: 15000000,
					},
				],
			},
			{
				id_loan_type: 'LOAN0007',
				name_loan_type: 'Multigriya',
				icon_loan_type: '',
				min_plafond: 3048103.0,
				default_term: 9,
				interest: [
					{
						id_master_loan_interest: 89,
						id_loan_type: 'LOAN0007',
						name_loan_type: 'Multigriya',
						id_grade: 'GRD001',
						name_grade: 'I',
						interest: 7.0,
					},
					{
						id_master_loan_interest: 90,
						id_loan_type: 'LOAN0007',
						name_loan_type: 'Multigriya',
						id_grade: 'GRD002',
						name_grade: 'II',
						interest: 7.0,
					},
					{
						id_master_loan_interest: 91,
						id_loan_type: 'LOAN0007',
						name_loan_type: 'Multigriya',
						id_grade: 'GRD003',
						name_grade: 'III',
						interest: 7.0,
					},
					{
						id_master_loan_interest: 92,
						id_loan_type: 'LOAN0007',
						name_loan_type: 'Multigriya',
						id_grade: 'GRD004',
						name_grade: 'IV',
						interest: 7.5,
					},
					{
						id_master_loan_interest: 93,
						id_loan_type: 'LOAN0007',
						name_loan_type: 'Multigriya',
						id_grade: 'GRD005',
						name_grade: 'V',
						interest: 7.5,
					},
					{
						id_master_loan_interest: 94,
						id_loan_type: 'LOAN0007',
						name_loan_type: 'Multigriya',
						id_grade: 'GRD006',
						name_grade: 'VI',
						interest: 7.5,
					},
					{
						id_master_loan_interest: 95,
						id_loan_type: 'LOAN0007',
						name_loan_type: 'Multigriya',
						id_grade: 'GRD007',
						name_grade: 'VII',
						interest: 7.5,
					},
				],
				plafond: [
					{
						id_master_loan_plafond: 71,
						id_grade: 'GRD001',
						name_grade: 'I',
						id_loan_type: 'LOAN0007',
						name_loan_type: 'Multigriya',
						loan_plafond: 75000000,
					},
					{
						id_master_loan_plafond: 85,
						id_grade: 'GRD002',
						name_grade: 'II',
						id_loan_type: 'LOAN0007',
						name_loan_type: 'Multigriya',
						loan_plafond: 75000000,
					},
					{
						id_master_loan_plafond: 99,
						id_grade: 'GRD003',
						name_grade: 'III',
						id_loan_type: 'LOAN0007',
						name_loan_type: 'Multigriya',
						loan_plafond: 75000000,
					},
					{
						id_master_loan_plafond: 113,
						id_grade: 'GRD004',
						name_grade: 'IV',
						id_loan_type: 'LOAN0007',
						name_loan_type: 'Multigriya',
						loan_plafond: 100000000,
					},
					{
						id_master_loan_plafond: 127,
						id_grade: 'GRD005',
						name_grade: 'V',
						id_loan_type: 'LOAN0007',
						name_loan_type: 'Multigriya',
						loan_plafond: 100000000,
					},
					{
						id_master_loan_plafond: 141,
						id_grade: 'GRD006',
						name_grade: 'VI',
						id_loan_type: 'LOAN0007',
						name_loan_type: 'Multigriya',
						loan_plafond: 100000000,
					},
					{
						id_master_loan_plafond: 155,
						id_grade: 'GRD007',
						name_grade: 'VII',
						id_loan_type: 'LOAN0007',
						name_loan_type: 'Multigriya',
						loan_plafond: 100000000,
					},
				],
			},
			{
				id_loan_type: 'LOAN0008',
				name_loan_type: 'Renovasi Rumah',
				icon_loan_type: '',
				min_plafond: 3048103.0,
				default_term: 9,
				interest: [
					{
						id_master_loan_interest: 96,
						id_loan_type: 'LOAN0008',
						name_loan_type: 'Renovasi Rumah',
						id_grade: 'GRD001',
						name_grade: 'I',
						interest: 7.5,
					},
					{
						id_master_loan_interest: 97,
						id_loan_type: 'LOAN0008',
						name_loan_type: 'Renovasi Rumah',
						id_grade: 'GRD002',
						name_grade: 'II',
						interest: 7.5,
					},
					{
						id_master_loan_interest: 98,
						id_loan_type: 'LOAN0008',
						name_loan_type: 'Renovasi Rumah',
						id_grade: 'GRD003',
						name_grade: 'III',
						interest: 7.5,
					},
					{
						id_master_loan_interest: 99,
						id_loan_type: 'LOAN0008',
						name_loan_type: 'Renovasi Rumah',
						id_grade: 'GRD004',
						name_grade: 'IV',
						interest: 8.0,
					},
					{
						id_master_loan_interest: 100,
						id_loan_type: 'LOAN0008',
						name_loan_type: 'Renovasi Rumah',
						id_grade: 'GRD005',
						name_grade: 'V',
						interest: 8.0,
					},
					{
						id_master_loan_interest: 101,
						id_loan_type: 'LOAN0008',
						name_loan_type: 'Renovasi Rumah',
						id_grade: 'GRD006',
						name_grade: 'VI',
						interest: 8.0,
					},
					{
						id_master_loan_interest: 102,
						id_loan_type: 'LOAN0008',
						name_loan_type: 'Renovasi Rumah',
						id_grade: 'GRD007',
						name_grade: 'VII',
						interest: 8.0,
					},
				],
				plafond: [
					{
						id_master_loan_plafond: 72,
						id_grade: 'GRD001',
						name_grade: 'I',
						id_loan_type: 'LOAN0008',
						name_loan_type: 'Renovasi Rumah',
						loan_plafond: 75000000,
					},
					{
						id_master_loan_plafond: 86,
						id_grade: 'GRD002',
						name_grade: 'II',
						id_loan_type: 'LOAN0008',
						name_loan_type: 'Renovasi Rumah',
						loan_plafond: 75000000,
					},
					{
						id_master_loan_plafond: 100,
						id_grade: 'GRD003',
						name_grade: 'III',
						id_loan_type: 'LOAN0008',
						name_loan_type: 'Renovasi Rumah',
						loan_plafond: 75000000,
					},
					{
						id_master_loan_plafond: 114,
						id_grade: 'GRD004',
						name_grade: 'IV',
						id_loan_type: 'LOAN0008',
						name_loan_type: 'Renovasi Rumah',
						loan_plafond: 100000000,
					},
					{
						id_master_loan_plafond: 128,
						id_grade: 'GRD005',
						name_grade: 'V',
						id_loan_type: 'LOAN0008',
						name_loan_type: 'Renovasi Rumah',
						loan_plafond: 100000000,
					},
					{
						id_master_loan_plafond: 142,
						id_grade: 'GRD006',
						name_grade: 'VI',
						id_loan_type: 'LOAN0008',
						name_loan_type: 'Renovasi Rumah',
						loan_plafond: 100000000,
					},
					{
						id_master_loan_plafond: 156,
						id_grade: 'GRD007',
						name_grade: 'VII',
						id_loan_type: 'LOAN0008',
						name_loan_type: 'Renovasi Rumah',
						loan_plafond: 100000000,
					},
				],
			},
			{
				id_loan_type: 'LOAN0009',
				name_loan_type: 'Griya Perdana',
				icon_loan_type: '',
				min_plafond: 3048103.0,
				default_term: 9,
				interest: [
					{
						id_master_loan_interest: 103,
						id_loan_type: 'LOAN0009',
						name_loan_type: 'Griya Perdana',
						id_grade: 'GRD001',
						name_grade: 'I',
						interest: 2.5,
					},
					{
						id_master_loan_interest: 104,
						id_loan_type: 'LOAN0009',
						name_loan_type: 'Griya Perdana',
						id_grade: 'GRD002',
						name_grade: 'II',
						interest: 2.5,
					},
					{
						id_master_loan_interest: 105,
						id_loan_type: 'LOAN0009',
						name_loan_type: 'Griya Perdana',
						id_grade: 'GRD003',
						name_grade: 'III',
						interest: 2.5,
					},
					{
						id_master_loan_interest: 106,
						id_loan_type: 'LOAN0009',
						name_loan_type: 'Griya Perdana',
						id_grade: 'GRD004',
						name_grade: 'IV',
						interest: 3.0,
					},
				],
				plafond: [
					{
						id_master_loan_plafond: 73,
						id_grade: 'GRD001',
						name_grade: 'I',
						id_loan_type: 'LOAN0009',
						name_loan_type: 'Griya Perdana',
						loan_plafond: 35000000,
					},
					{
						id_master_loan_plafond: 87,
						id_grade: 'GRD002',
						name_grade: 'II',
						id_loan_type: 'LOAN0009',
						name_loan_type: 'Griya Perdana',
						loan_plafond: 35000000,
					},
					{
						id_master_loan_plafond: 101,
						id_grade: 'GRD003',
						name_grade: 'III',
						id_loan_type: 'LOAN0009',
						name_loan_type: 'Griya Perdana',
						loan_plafond: 35000000,
					},
					{
						id_master_loan_plafond: 115,
						id_grade: 'GRD004',
						name_grade: 'IV',
						id_loan_type: 'LOAN0009',
						name_loan_type: 'Griya Perdana',
						loan_plafond: 50000000,
					},
				],
			},
			{
				id_loan_type: 'LOAN0010',
				name_loan_type: 'Darurat',
				icon_loan_type: '',
				min_plafond: 3048103.0,
				default_term: 9,
				interest: [
					{
						id_master_loan_interest: 110,
						id_loan_type: 'LOAN0010',
						name_loan_type: 'Darurat',
						id_grade: 'GRD001',
						name_grade: 'I',
						interest: 4.5,
					},
					{
						id_master_loan_interest: 111,
						id_loan_type: 'LOAN0010',
						name_loan_type: 'Darurat',
						id_grade: 'GRD002',
						name_grade: 'II',
						interest: 4.5,
					},
					{
						id_master_loan_interest: 112,
						id_loan_type: 'LOAN0010',
						name_loan_type: 'Darurat',
						id_grade: 'GRD003',
						name_grade: 'III',
						interest: 4.5,
					},
					{
						id_master_loan_interest: 113,
						id_loan_type: 'LOAN0010',
						name_loan_type: 'Darurat',
						id_grade: 'GRD004',
						name_grade: 'IV',
						interest: 5.0,
					},
					{
						id_master_loan_interest: 114,
						id_loan_type: 'LOAN0010',
						name_loan_type: 'Darurat',
						id_grade: 'GRD005',
						name_grade: 'V',
						interest: 5.0,
					},
					{
						id_master_loan_interest: 115,
						id_loan_type: 'LOAN0010',
						name_loan_type: 'Darurat',
						id_grade: 'GRD006',
						name_grade: 'VI',
						interest: 5.0,
					},
					{
						id_master_loan_interest: 116,
						id_loan_type: 'LOAN0010',
						name_loan_type: 'Darurat',
						id_grade: 'GRD007',
						name_grade: 'VII',
						interest: 5.0,
					},
				],
				plafond: [
					{
						id_master_loan_plafond: 74,
						id_grade: 'GRD001',
						name_grade: 'I',
						id_loan_type: 'LOAN0010',
						name_loan_type: 'Darurat',
						loan_plafond: 30000000,
					},
					{
						id_master_loan_plafond: 88,
						id_grade: 'GRD002',
						name_grade: 'II',
						id_loan_type: 'LOAN0010',
						name_loan_type: 'Darurat',
						loan_plafond: 30000000,
					},
					{
						id_master_loan_plafond: 102,
						id_grade: 'GRD003',
						name_grade: 'III',
						id_loan_type: 'LOAN0010',
						name_loan_type: 'Darurat',
						loan_plafond: 30000000,
					},
					{
						id_master_loan_plafond: 116,
						id_grade: 'GRD004',
						name_grade: 'IV',
						id_loan_type: 'LOAN0010',
						name_loan_type: 'Darurat',
						loan_plafond: 50000000,
					},
					{
						id_master_loan_plafond: 130,
						id_grade: 'GRD005',
						name_grade: 'V',
						id_loan_type: 'LOAN0010',
						name_loan_type: 'Darurat',
						loan_plafond: 50000000,
					},
					{
						id_master_loan_plafond: 144,
						id_grade: 'GRD006',
						name_grade: 'VI',
						id_loan_type: 'LOAN0010',
						name_loan_type: 'Darurat',
						loan_plafond: 50000000,
					},
					{
						id_master_loan_plafond: 158,
						id_grade: 'GRD007',
						name_grade: 'VII',
						id_loan_type: 'LOAN0010',
						name_loan_type: 'Darurat',
						loan_plafond: 50000000,
					},
				],
			},
			{
				id_loan_type: 'LOAN0011',
				name_loan_type: 'Pendidikan',
				icon_loan_type: '',
				min_plafond: 3048103.0,
				default_term: 9,
				interest: [
					{
						id_master_loan_interest: 117,
						id_loan_type: 'LOAN0011',
						name_loan_type: 'Pendidikan',
						id_grade: 'GRD001',
						name_grade: 'I',
						interest: 4.5,
					},
					{
						id_master_loan_interest: 118,
						id_loan_type: 'LOAN0011',
						name_loan_type: 'Pendidikan',
						id_grade: 'GRD002',
						name_grade: 'II',
						interest: 4.5,
					},
					{
						id_master_loan_interest: 119,
						id_loan_type: 'LOAN0011',
						name_loan_type: 'Pendidikan',
						id_grade: 'GRD003',
						name_grade: 'III',
						interest: 4.5,
					},
					{
						id_master_loan_interest: 120,
						id_loan_type: 'LOAN0011',
						name_loan_type: 'Pendidikan',
						id_grade: 'GRD004',
						name_grade: 'IV',
						interest: 5.0,
					},
				],
				plafond: [
					{
						id_master_loan_plafond: 75,
						id_grade: 'GRD001',
						name_grade: 'I',
						id_loan_type: 'LOAN0011',
						name_loan_type: 'Pendidikan',
						loan_plafond: 30000000,
					},
					{
						id_master_loan_plafond: 89,
						id_grade: 'GRD002',
						name_grade: 'II',
						id_loan_type: 'LOAN0011',
						name_loan_type: 'Pendidikan',
						loan_plafond: 30000000,
					},
					{
						id_master_loan_plafond: 103,
						id_grade: 'GRD003',
						name_grade: 'III',
						id_loan_type: 'LOAN0011',
						name_loan_type: 'Pendidikan',
						loan_plafond: 30000000,
					},
					{
						id_master_loan_plafond: 117,
						id_grade: 'GRD004',
						name_grade: 'IV',
						id_loan_type: 'LOAN0011',
						name_loan_type: 'Pendidikan',
						loan_plafond: 50000000,
					},
				],
			},
			{
				id_loan_type: 'LOAN0012',
				name_loan_type: 'Peduli Bencana',
				icon_loan_type: '',
				min_plafond: 3048103.0,
				default_term: 9,
				interest: [
					{
						id_master_loan_interest: 124,
						id_loan_type: 'LOAN0012',
						name_loan_type: 'Peduli Bencana',
						id_grade: 'GRD001',
						name_grade: 'I',
						interest: 2.0,
					},
					{
						id_master_loan_interest: 125,
						id_loan_type: 'LOAN0012',
						name_loan_type: 'Peduli Bencana',
						id_grade: 'GRD002',
						name_grade: 'II',
						interest: 2.0,
					},
					{
						id_master_loan_interest: 126,
						id_loan_type: 'LOAN0012',
						name_loan_type: 'Peduli Bencana',
						id_grade: 'GRD003',
						name_grade: 'III',
						interest: 2.0,
					},
					{
						id_master_loan_interest: 127,
						id_loan_type: 'LOAN0012',
						name_loan_type: 'Peduli Bencana',
						id_grade: 'GRD004',
						name_grade: 'IV',
						interest: 2.5,
					},
					{
						id_master_loan_interest: 128,
						id_loan_type: 'LOAN0012',
						name_loan_type: 'Peduli Bencana',
						id_grade: 'GRD005',
						name_grade: 'V',
						interest: 2.5,
					},
					{
						id_master_loan_interest: 129,
						id_loan_type: 'LOAN0012',
						name_loan_type: 'Peduli Bencana',
						id_grade: 'GRD006',
						name_grade: 'VI',
						interest: 2.5,
					},
					{
						id_master_loan_interest: 130,
						id_loan_type: 'LOAN0012',
						name_loan_type: 'Peduli Bencana',
						id_grade: 'GRD007',
						name_grade: 'VII',
						interest: 2.5,
					},
				],
				plafond: [
					{
						id_master_loan_plafond: 76,
						id_grade: 'GRD001',
						name_grade: 'I',
						id_loan_type: 'LOAN0012',
						name_loan_type: 'Peduli Bencana',
						loan_plafond: 10000000,
					},
					{
						id_master_loan_plafond: 90,
						id_grade: 'GRD002',
						name_grade: 'II',
						id_loan_type: 'LOAN0012',
						name_loan_type: 'Peduli Bencana',
						loan_plafond: 10000000,
					},
					{
						id_master_loan_plafond: 104,
						id_grade: 'GRD003',
						name_grade: 'III',
						id_loan_type: 'LOAN0012',
						name_loan_type: 'Peduli Bencana',
						loan_plafond: 10000000,
					},
					{
						id_master_loan_plafond: 118,
						id_grade: 'GRD004',
						name_grade: 'IV',
						id_loan_type: 'LOAN0012',
						name_loan_type: 'Peduli Bencana',
						loan_plafond: 15000000,
					},
					{
						id_master_loan_plafond: 132,
						id_grade: 'GRD005',
						name_grade: 'V',
						id_loan_type: 'LOAN0012',
						name_loan_type: 'Peduli Bencana',
						loan_plafond: 15000000,
					},
					{
						id_master_loan_plafond: 146,
						id_grade: 'GRD006',
						name_grade: 'VI',
						id_loan_type: 'LOAN0012',
						name_loan_type: 'Peduli Bencana',
						loan_plafond: 15000000,
					},
					{
						id_master_loan_plafond: 160,
						id_grade: 'GRD007',
						name_grade: 'VII',
						id_loan_type: 'LOAN0012',
						name_loan_type: 'Peduli Bencana',
						loan_plafond: 15000000,
					},
				],
			},
			{
				id_loan_type: 'LOAN0013',
				name_loan_type: 'Pelangi Keluarga',
				icon_loan_type: '',
				min_plafond: 3048103.0,
				default_term: 9,
				interest: [
					{
						id_master_loan_interest: 131,
						id_loan_type: 'LOAN0013',
						name_loan_type: 'Pelangi Keluarga',
						id_grade: 'GRD001',
						name_grade: 'I',
						interest: 4.5,
					},
					{
						id_master_loan_interest: 132,
						id_loan_type: 'LOAN0013',
						name_loan_type: 'Pelangi Keluarga',
						id_grade: 'GRD002',
						name_grade: 'II',
						interest: 4.5,
					},
					{
						id_master_loan_interest: 133,
						id_loan_type: 'LOAN0013',
						name_loan_type: 'Pelangi Keluarga',
						id_grade: 'GRD003',
						name_grade: 'III',
						interest: 4.5,
					},
					{
						id_master_loan_interest: 134,
						id_loan_type: 'LOAN0013',
						name_loan_type: 'Pelangi Keluarga',
						id_grade: 'GRD004',
						name_grade: 'IV',
						interest: 5.0,
					},
					{
						id_master_loan_interest: 135,
						id_loan_type: 'LOAN0013',
						name_loan_type: 'Pelangi Keluarga',
						id_grade: 'GRD005',
						name_grade: 'V',
						interest: 5.0,
					},
					{
						id_master_loan_interest: 136,
						id_loan_type: 'LOAN0013',
						name_loan_type: 'Pelangi Keluarga',
						id_grade: 'GRD006',
						name_grade: 'VI',
						interest: 5.0,
					},
					{
						id_master_loan_interest: 137,
						id_loan_type: 'LOAN0013',
						name_loan_type: 'Pelangi Keluarga',
						id_grade: 'GRD007',
						name_grade: 'VII',
						interest: 5.0,
					},
				],
				plafond: [
					{
						id_master_loan_plafond: 77,
						id_grade: 'GRD001',
						name_grade: 'I',
						id_loan_type: 'LOAN0013',
						name_loan_type: 'Pelangi Keluarga',
						loan_plafond: 15000000,
					},
					{
						id_master_loan_plafond: 91,
						id_grade: 'GRD002',
						name_grade: 'II',
						id_loan_type: 'LOAN0013',
						name_loan_type: 'Pelangi Keluarga',
						loan_plafond: 15000000,
					},
					{
						id_master_loan_plafond: 105,
						id_grade: 'GRD003',
						name_grade: 'III',
						id_loan_type: 'LOAN0013',
						name_loan_type: 'Pelangi Keluarga',
						loan_plafond: 15000000,
					},
					{
						id_master_loan_plafond: 119,
						id_grade: 'GRD004',
						name_grade: 'IV',
						id_loan_type: 'LOAN0013',
						name_loan_type: 'Pelangi Keluarga',
						loan_plafond: 20000000,
					},
					{
						id_master_loan_plafond: 133,
						id_grade: 'GRD005',
						name_grade: 'V',
						id_loan_type: 'LOAN0013',
						name_loan_type: 'Pelangi Keluarga',
						loan_plafond: 20000000,
					},
					{
						id_master_loan_plafond: 147,
						id_grade: 'GRD006',
						name_grade: 'VI',
						id_loan_type: 'LOAN0013',
						name_loan_type: 'Pelangi Keluarga',
						loan_plafond: 20000000,
					},
					{
						id_master_loan_plafond: 161,
						id_grade: 'GRD007',
						name_grade: 'VII',
						id_loan_type: 'LOAN0013',
						name_loan_type: 'Pelangi Keluarga',
						loan_plafond: 20000000,
					},
				],
			},
			{
				id_loan_type: 'LOAN0014',
				name_loan_type: 'Modal Usaha Keluarga',
				icon_loan_type: '',
				min_plafond: 3048103.0,
				default_term: 9,
				interest: [
					{
						id_master_loan_interest: 138,
						id_loan_type: 'LOAN0014',
						name_loan_type: 'Modal Usaha Keluarga',
						id_grade: 'GRD001',
						name_grade: 'I',
						interest: 7.5,
					},
					{
						id_master_loan_interest: 139,
						id_loan_type: 'LOAN0014',
						name_loan_type: 'Modal Usaha Keluarga',
						id_grade: 'GRD002',
						name_grade: 'II',
						interest: 7.5,
					},
					{
						id_master_loan_interest: 140,
						id_loan_type: 'LOAN0014',
						name_loan_type: 'Modal Usaha Keluarga',
						id_grade: 'GRD003',
						name_grade: 'III',
						interest: 7.5,
					},
					{
						id_master_loan_interest: 141,
						id_loan_type: 'LOAN0014',
						name_loan_type: 'Modal Usaha Keluarga',
						id_grade: 'GRD004',
						name_grade: 'IV',
						interest: 8.0,
					},
					{
						id_master_loan_interest: 142,
						id_loan_type: 'LOAN0014',
						name_loan_type: 'Modal Usaha Keluarga',
						id_grade: 'GRD005',
						name_grade: 'V',
						interest: 8.0,
					},
					{
						id_master_loan_interest: 143,
						id_loan_type: 'LOAN0014',
						name_loan_type: 'Modal Usaha Keluarga',
						id_grade: 'GRD006',
						name_grade: 'VI',
						interest: 8.0,
					},
					{
						id_master_loan_interest: 144,
						id_loan_type: 'LOAN0014',
						name_loan_type: 'Modal Usaha Keluarga',
						id_grade: 'GRD007',
						name_grade: 'VII',
						interest: 8.0,
					},
				],
				plafond: [
					{
						id_master_loan_plafond: 78,
						id_grade: 'GRD001',
						name_grade: 'I',
						id_loan_type: 'LOAN0014',
						name_loan_type: 'Modal Usaha Keluarga',
						loan_plafond: 30000000,
					},
					{
						id_master_loan_plafond: 92,
						id_grade: 'GRD002',
						name_grade: 'II',
						id_loan_type: 'LOAN0014',
						name_loan_type: 'Modal Usaha Keluarga',
						loan_plafond: 30000000,
					},
					{
						id_master_loan_plafond: 106,
						id_grade: 'GRD003',
						name_grade: 'III',
						id_loan_type: 'LOAN0014',
						name_loan_type: 'Modal Usaha Keluarga',
						loan_plafond: 30000000,
					},
					{
						id_master_loan_plafond: 120,
						id_grade: 'GRD004',
						name_grade: 'IV',
						id_loan_type: 'LOAN0014',
						name_loan_type: 'Modal Usaha Keluarga',
						loan_plafond: 50000000,
					},
					{
						id_master_loan_plafond: 134,
						id_grade: 'GRD005',
						name_grade: 'V',
						id_loan_type: 'LOAN0014',
						name_loan_type: 'Modal Usaha Keluarga',
						loan_plafond: 50000000,
					},
					{
						id_master_loan_plafond: 148,
						id_grade: 'GRD006',
						name_grade: 'VI',
						id_loan_type: 'LOAN0014',
						name_loan_type: 'Modal Usaha Keluarga',
						loan_plafond: 50000000,
					},
					{
						id_master_loan_plafond: 162,
						id_grade: 'GRD007',
						name_grade: 'VII',
						id_loan_type: 'LOAN0014',
						name_loan_type: 'Modal Usaha Keluarga',
						loan_plafond: 50000000,
					},
				],
			},
			{
				id_loan_type: 'LOAN0015',
				name_loan_type: 'First Loan',
				icon_loan_type: '',
				min_plafond: 3048103.0,
				default_term: 9,
				interest: [
					{
						id_master_loan_interest: 254,
						id_loan_type: 'LOAN0015',
						name_loan_type: 'First Loan',
						id_grade: 'GRD001',
						name_grade: 'I',
						interest: 8.5,
					},
					{
						id_master_loan_interest: 255,
						id_loan_type: 'LOAN0015',
						name_loan_type: 'First Loan',
						id_grade: 'GRD002',
						name_grade: 'II',
						interest: 8.5,
					},
					{
						id_master_loan_interest: 256,
						id_loan_type: 'LOAN0015',
						name_loan_type: 'First Loan',
						id_grade: 'GRD003',
						name_grade: 'III',
						interest: 8.5,
					},
					{
						id_master_loan_interest: 257,
						id_loan_type: 'LOAN0015',
						name_loan_type: 'First Loan',
						id_grade: 'GRD004',
						name_grade: 'IV',
						interest: 9.0,
					},
					{
						id_master_loan_interest: 258,
						id_loan_type: 'LOAN0015',
						name_loan_type: 'First Loan',
						id_grade: 'GRD005',
						name_grade: 'V',
						interest: 9.0,
					},
					{
						id_master_loan_interest: 259,
						id_loan_type: 'LOAN0015',
						name_loan_type: 'First Loan',
						id_grade: 'GRD006',
						name_grade: 'VI',
						interest: 9.0,
					},
					{
						id_master_loan_interest: 260,
						id_loan_type: 'LOAN0015',
						name_loan_type: 'First Loan',
						id_grade: 'GRD007',
						name_grade: 'VII',
						interest: 9.0,
					},
				],
				plafond: [
					{
						id_master_loan_plafond: 192,
						id_grade: 'GRD001',
						name_grade: 'I',
						id_loan_type: 'LOAN0015',
						name_loan_type: 'First Loan',
						loan_plafond: 5000000,
					},
					{
						id_master_loan_plafond: 193,
						id_grade: 'GRD002',
						name_grade: 'II',
						id_loan_type: 'LOAN0015',
						name_loan_type: 'First Loan',
						loan_plafond: 5000000,
					},
					{
						id_master_loan_plafond: 194,
						id_grade: 'GRD003',
						name_grade: 'III',
						id_loan_type: 'LOAN0015',
						name_loan_type: 'First Loan',
						loan_plafond: 5000000,
					},
					{
						id_master_loan_plafond: 195,
						id_grade: 'GRD004',
						name_grade: 'IV',
						id_loan_type: 'LOAN0015',
						name_loan_type: 'First Loan',
						loan_plafond: 150000000,
					},
					{
						id_master_loan_plafond: 196,
						id_grade: 'GRD005',
						name_grade: 'V',
						id_loan_type: 'LOAN0015',
						name_loan_type: 'First Loan',
						loan_plafond: 200000000,
					},
					{
						id_master_loan_plafond: 197,
						id_grade: 'GRD006',
						name_grade: 'VI',
						id_loan_type: 'LOAN0015',
						name_loan_type: 'First Loan',
						loan_plafond: 200000000,
					},
					{
						id_master_loan_plafond: 198,
						id_grade: 'GRD007',
						name_grade: 'VII',
						id_loan_type: 'LOAN0015',
						name_loan_type: 'First Loan',
						loan_plafond: 200000000,
					},
				],
			},
			{
				id_loan_type: 'LOAN0016',
				name_loan_type: 'Fleksi 20',
				icon_loan_type: '',
				min_plafond: 3048103.0,
				default_term: 9,
				interest: [
					{
						id_master_loan_interest: 168,
						id_loan_type: 'LOAN0016',
						name_loan_type: 'Fleksi 20',
						id_grade: 'GRD004',
						name_grade: 'IV',
						interest: 9.0,
					},
				],
				plafond: [
					{
						id_master_loan_plafond: 199,
						id_grade: 'GRD004',
						name_grade: 'IV',
						id_loan_type: 'LOAN0016',
						name_loan_type: 'Fleksi 20',
						loan_plafond: 50000000,
					},
				],
			},
			{
				id_loan_type: 'LOAN0017',
				name_loan_type: 'Fleksi 80',
				icon_loan_type: '',
				min_plafond: 3048103.0,
				default_term: 9,
				interest: [
					{
						id_master_loan_interest: 169,
						id_loan_type: 'LOAN0017',
						name_loan_type: 'Fleksi 80',
						id_grade: 'GRD004',
						name_grade: 'IV',
						interest: 9.0,
					},
				],
				plafond: [
					{
						id_master_loan_plafond: 200,
						id_grade: 'GRD004',
						name_grade: 'IV',
						id_loan_type: 'LOAN0017',
						name_loan_type: 'Fleksi 80',
						loan_plafond: 200000000,
					},
				],
			},
			{
				id_loan_type: 'LOAN0018',
				name_loan_type: 'Priority 20',
				icon_loan_type: '',
				min_plafond: 3048103.0,
				default_term: 9,
				interest: [
					{
						id_master_loan_interest: 170,
						id_loan_type: 'LOAN0018',
						name_loan_type: 'Priority 20',
						id_grade: 'GRD005',
						name_grade: 'V',
						interest: 9.0,
					},
					{
						id_master_loan_interest: 171,
						id_loan_type: 'LOAN0018',
						name_loan_type: 'Priority 20',
						id_grade: 'GRD006',
						name_grade: 'VI',
						interest: 9.0,
					},
					{
						id_master_loan_interest: 172,
						id_loan_type: 'LOAN0018',
						name_loan_type: 'Priority 20',
						id_grade: 'GRD007',
						name_grade: 'VII',
						interest: 9.0,
					},
				],
				plafond: [
					{
						id_master_loan_plafond: 201,
						id_grade: 'GRD005',
						name_grade: 'V',
						id_loan_type: 'LOAN0018',
						name_loan_type: 'Priority 20',
						loan_plafond: 150000000,
					},
					{
						id_master_loan_plafond: 202,
						id_grade: 'GRD006',
						name_grade: 'VI',
						id_loan_type: 'LOAN0018',
						name_loan_type: 'Priority 20',
						loan_plafond: 150000000,
					},
					{
						id_master_loan_plafond: 203,
						id_grade: 'GRD007',
						name_grade: 'VII',
						id_loan_type: 'LOAN0018',
						name_loan_type: 'Priority 20',
						loan_plafond: 150000000,
					},
				],
			},
			{
				id_loan_type: 'LOAN0019',
				name_loan_type: 'Priority 80',
				icon_loan_type: '',
				min_plafond: 3048103.0,
				default_term: 9,
				interest: [
					{
						id_master_loan_interest: 173,
						id_loan_type: 'LOAN0019',
						name_loan_type: 'Priority 80',
						id_grade: 'GRD005',
						name_grade: 'V',
						interest: 9.0,
					},
					{
						id_master_loan_interest: 174,
						id_loan_type: 'LOAN0019',
						name_loan_type: 'Priority 80',
						id_grade: 'GRD006',
						name_grade: 'VI',
						interest: 9.0,
					},
					{
						id_master_loan_interest: 175,
						id_loan_type: 'LOAN0019',
						name_loan_type: 'Priority 80',
						id_grade: 'GRD007',
						name_grade: 'VII',
						interest: 9.0,
					},
				],
				plafond: [
					{
						id_master_loan_plafond: 204,
						id_grade: 'GRD005',
						name_grade: 'V',
						id_loan_type: 'LOAN0019',
						name_loan_type: 'Priority 80',
						loan_plafond: 600000000,
					},
					{
						id_master_loan_plafond: 205,
						id_grade: 'GRD006',
						name_grade: 'VI',
						id_loan_type: 'LOAN0019',
						name_loan_type: 'Priority 80',
						loan_plafond: 600000000,
					},
					{
						id_master_loan_plafond: 206,
						id_grade: 'GRD007',
						name_grade: 'VII',
						id_loan_type: 'LOAN0019',
						name_loan_type: 'Priority 80',
						loan_plafond: 600000000,
					},
				],
			},
			{
				id_loan_type: 'LOAN0021',
				name_loan_type: 'Pendidikan ELP1\r\n',
				icon_loan_type: '',
				min_plafond: 3048103.0,
				default_term: 9,
				interest: [
					{
						id_master_loan_interest: 183,
						id_loan_type: 'LOAN0021',
						name_loan_type: 'Pendidikan ELP1\r\n',
						id_grade: 'GRD001',
						name_grade: 'I',
						interest: 4.5,
					},
					{
						id_master_loan_interest: 184,
						id_loan_type: 'LOAN0021',
						name_loan_type: 'Pendidikan ELP1\r\n',
						id_grade: 'GRD002',
						name_grade: 'II',
						interest: 4.5,
					},
					{
						id_master_loan_interest: 185,
						id_loan_type: 'LOAN0021',
						name_loan_type: 'Pendidikan ELP1\r\n',
						id_grade: 'GRD003',
						name_grade: 'III',
						interest: 4.5,
					},
					{
						id_master_loan_interest: 186,
						id_loan_type: 'LOAN0021',
						name_loan_type: 'Pendidikan ELP1\r\n',
						id_grade: 'GRD004',
						name_grade: 'IV',
						interest: 4.5,
					},
					{
						id_master_loan_interest: 187,
						id_loan_type: 'LOAN0021',
						name_loan_type: 'Pendidikan ELP1\r\n',
						id_grade: 'GRD005',
						name_grade: 'V',
						interest: 4.5,
					},
					{
						id_master_loan_interest: 188,
						id_loan_type: 'LOAN0021',
						name_loan_type: 'Pendidikan ELP1\r\n',
						id_grade: 'GRD006',
						name_grade: 'VI',
						interest: 4.5,
					},
					{
						id_master_loan_interest: 189,
						id_loan_type: 'LOAN0021',
						name_loan_type: 'Pendidikan ELP1\r\n',
						id_grade: 'GRD007',
						name_grade: 'VII',
						interest: 4.5,
					},
				],
				plafond: [
					{
						id_master_loan_plafond: 214,
						id_grade: 'GRD001',
						name_grade: 'I',
						id_loan_type: 'LOAN0021',
						name_loan_type: 'Pendidikan ELP1\r\n',
						loan_plafond: 30000000,
					},
					{
						id_master_loan_plafond: 215,
						id_grade: 'GRD002',
						name_grade: 'II',
						id_loan_type: 'LOAN0021',
						name_loan_type: 'Pendidikan ELP1\r\n',
						loan_plafond: 30000000,
					},
					{
						id_master_loan_plafond: 216,
						id_grade: 'GRD003',
						name_grade: 'III',
						id_loan_type: 'LOAN0021',
						name_loan_type: 'Pendidikan ELP1\r\n',
						loan_plafond: 30000000,
					},
					{
						id_master_loan_plafond: 217,
						id_grade: 'GRD004',
						name_grade: 'IV',
						id_loan_type: 'LOAN0021',
						name_loan_type: 'Pendidikan ELP1\r\n',
						loan_plafond: 30000000,
					},
					{
						id_master_loan_plafond: 218,
						id_grade: 'GRD005',
						name_grade: 'V',
						id_loan_type: 'LOAN0021',
						name_loan_type: 'Pendidikan ELP1\r\n',
						loan_plafond: 30000000,
					},
					{
						id_master_loan_plafond: 219,
						id_grade: 'GRD006',
						name_grade: 'VI',
						id_loan_type: 'LOAN0021',
						name_loan_type: 'Pendidikan ELP1\r\n',
						loan_plafond: 30000000,
					},
					{
						id_master_loan_plafond: 220,
						id_grade: 'GRD007',
						name_grade: 'VII',
						id_loan_type: 'LOAN0021',
						name_loan_type: 'Pendidikan ELP1\r\n',
						loan_plafond: 30000000,
					},
				],
			},
			{
				id_loan_type: 'LOAN0022',
				name_loan_type: 'Pendidikan ELP2',
				icon_loan_type: '',
				min_plafond: 3048103.0,
				default_term: 9,
				interest: [
					{
						id_master_loan_interest: 190,
						id_loan_type: 'LOAN0022',
						name_loan_type: 'Pendidikan ELP2',
						id_grade: 'GRD001',
						name_grade: 'I',
						interest: 5.0,
					},
					{
						id_master_loan_interest: 191,
						id_loan_type: 'LOAN0022',
						name_loan_type: 'Pendidikan ELP2',
						id_grade: 'GRD002',
						name_grade: 'II',
						interest: 5.0,
					},
					{
						id_master_loan_interest: 192,
						id_loan_type: 'LOAN0022',
						name_loan_type: 'Pendidikan ELP2',
						id_grade: 'GRD003',
						name_grade: 'III',
						interest: 5.0,
					},
					{
						id_master_loan_interest: 193,
						id_loan_type: 'LOAN0022',
						name_loan_type: 'Pendidikan ELP2',
						id_grade: 'GRD004',
						name_grade: 'IV',
						interest: 5.0,
					},
					{
						id_master_loan_interest: 194,
						id_loan_type: 'LOAN0022',
						name_loan_type: 'Pendidikan ELP2',
						id_grade: 'GRD005',
						name_grade: 'V',
						interest: 5.0,
					},
					{
						id_master_loan_interest: 195,
						id_loan_type: 'LOAN0022',
						name_loan_type: 'Pendidikan ELP2',
						id_grade: 'GRD006',
						name_grade: 'VI',
						interest: 5.0,
					},
					{
						id_master_loan_interest: 196,
						id_loan_type: 'LOAN0022',
						name_loan_type: 'Pendidikan ELP2',
						id_grade: 'GRD007',
						name_grade: 'VII',
						interest: 5.0,
					},
				],
				plafond: [
					{
						id_master_loan_plafond: 221,
						id_grade: 'GRD001',
						name_grade: 'I',
						id_loan_type: 'LOAN0022',
						name_loan_type: 'Pendidikan ELP2',
						loan_plafond: 50000000,
					},
					{
						id_master_loan_plafond: 222,
						id_grade: 'GRD002',
						name_grade: 'II',
						id_loan_type: 'LOAN0022',
						name_loan_type: 'Pendidikan ELP2',
						loan_plafond: 50000000,
					},
					{
						id_master_loan_plafond: 223,
						id_grade: 'GRD003',
						name_grade: 'III',
						id_loan_type: 'LOAN0022',
						name_loan_type: 'Pendidikan ELP2',
						loan_plafond: 50000000,
					},
					{
						id_master_loan_plafond: 224,
						id_grade: 'GRD004',
						name_grade: 'IV',
						id_loan_type: 'LOAN0022',
						name_loan_type: 'Pendidikan ELP2',
						loan_plafond: 50000000,
					},
					{
						id_master_loan_plafond: 225,
						id_grade: 'GRD005',
						name_grade: 'V',
						id_loan_type: 'LOAN0022',
						name_loan_type: 'Pendidikan ELP2',
						loan_plafond: 50000000,
					},
				],
			},
			{
				id_loan_type: 'LOAN0023',
				name_loan_type: 'Pendidikan ELP3',
				icon_loan_type: '',
				min_plafond: 3048103.0,
				default_term: 9,
				interest: [
					{
						id_master_loan_interest: 197,
						id_loan_type: 'LOAN0023',
						name_loan_type: 'Pendidikan ELP3',
						id_grade: 'GRD001',
						name_grade: 'I',
						interest: 6.0,
					},
					{
						id_master_loan_interest: 198,
						id_loan_type: 'LOAN0023',
						name_loan_type: 'Pendidikan ELP3',
						id_grade: 'GRD002',
						name_grade: 'II',
						interest: 6.0,
					},
					{
						id_master_loan_interest: 199,
						id_loan_type: 'LOAN0023',
						name_loan_type: 'Pendidikan ELP3',
						id_grade: 'GRD003',
						name_grade: 'III',
						interest: 6.0,
					},
					{
						id_master_loan_interest: 200,
						id_loan_type: 'LOAN0023',
						name_loan_type: 'Pendidikan ELP3',
						id_grade: 'GRD004',
						name_grade: 'IV',
						interest: 6.0,
					},
					{
						id_master_loan_interest: 201,
						id_loan_type: 'LOAN0023',
						name_loan_type: 'Pendidikan ELP3',
						id_grade: 'GRD005',
						name_grade: 'V',
						interest: 6.0,
					},
					{
						id_master_loan_interest: 202,
						id_loan_type: 'LOAN0023',
						name_loan_type: 'Pendidikan ELP3',
						id_grade: 'GRD006',
						name_grade: 'VI',
						interest: 6.0,
					},
					{
						id_master_loan_interest: 203,
						id_loan_type: 'LOAN0023',
						name_loan_type: 'Pendidikan ELP3',
						id_grade: 'GRD007',
						name_grade: 'VII',
						interest: 6.0,
					},
				],
				plafond: [
					{
						id_master_loan_plafond: 226,
						id_grade: 'GRD001',
						name_grade: 'I',
						id_loan_type: 'LOAN0023',
						name_loan_type: 'Pendidikan ELP3',
						loan_plafond: 100000000,
					},
					{
						id_master_loan_plafond: 227,
						id_grade: 'GRD002',
						name_grade: 'II',
						id_loan_type: 'LOAN0023',
						name_loan_type: 'Pendidikan ELP3',
						loan_plafond: 100000000,
					},
					{
						id_master_loan_plafond: 228,
						id_grade: 'GRD003',
						name_grade: 'III',
						id_loan_type: 'LOAN0023',
						name_loan_type: 'Pendidikan ELP3',
						loan_plafond: 100000000,
					},
					{
						id_master_loan_plafond: 229,
						id_grade: 'GRD004',
						name_grade: 'IV',
						id_loan_type: 'LOAN0023',
						name_loan_type: 'Pendidikan ELP3',
						loan_plafond: 100000000,
					},
					{
						id_master_loan_plafond: 230,
						id_grade: 'GRD005',
						name_grade: 'V',
						id_loan_type: 'LOAN0023',
						name_loan_type: 'Pendidikan ELP3',
						loan_plafond: 100000000,
					},
					{
						id_master_loan_plafond: 231,
						id_grade: 'GRD006',
						name_grade: 'VI',
						id_loan_type: 'LOAN0023',
						name_loan_type: 'Pendidikan ELP3',
						loan_plafond: 100000000,
					},
					{
						id_master_loan_plafond: 232,
						id_grade: 'GRD007',
						name_grade: 'VII',
						id_loan_type: 'LOAN0023',
						name_loan_type: 'Pendidikan ELP3',
						loan_plafond: 100000000,
					},
				],
			},
			{
				id_loan_type: 'LOAN0024',
				name_loan_type: 'Pendidikan ELP4',
				icon_loan_type: '',
				min_plafond: 3048103.0,
				default_term: 9,
				interest: [
					{
						id_master_loan_interest: 204,
						id_loan_type: 'LOAN0024',
						name_loan_type: 'Pendidikan ELP4',
						id_grade: 'GRD001',
						name_grade: 'I',
						interest: 6.5,
					},
					{
						id_master_loan_interest: 205,
						id_loan_type: 'LOAN0024',
						name_loan_type: 'Pendidikan ELP4',
						id_grade: 'GRD002',
						name_grade: 'II',
						interest: 6.5,
					},
					{
						id_master_loan_interest: 206,
						id_loan_type: 'LOAN0024',
						name_loan_type: 'Pendidikan ELP4',
						id_grade: 'GRD003',
						name_grade: 'III',
						interest: 6.5,
					},
					{
						id_master_loan_interest: 207,
						id_loan_type: 'LOAN0024',
						name_loan_type: 'Pendidikan ELP4',
						id_grade: 'GRD004',
						name_grade: 'IV',
						interest: 6.5,
					},
					{
						id_master_loan_interest: 208,
						id_loan_type: 'LOAN0024',
						name_loan_type: 'Pendidikan ELP4',
						id_grade: 'GRD005',
						name_grade: 'V',
						interest: 6.5,
					},
					{
						id_master_loan_interest: 209,
						id_loan_type: 'LOAN0024',
						name_loan_type: 'Pendidikan ELP4',
						id_grade: 'GRD006',
						name_grade: 'VI',
						interest: 6.5,
					},
					{
						id_master_loan_interest: 210,
						id_loan_type: 'LOAN0024',
						name_loan_type: 'Pendidikan ELP4',
						id_grade: 'GRD007',
						name_grade: 'VII',
						interest: 6.5,
					},
				],
				plafond: [
					{
						id_master_loan_plafond: 233,
						id_grade: 'GRD001',
						name_grade: 'I',
						id_loan_type: 'LOAN0024',
						name_loan_type: 'Pendidikan ELP4',
						loan_plafond: 300000000,
					},
					{
						id_master_loan_plafond: 234,
						id_grade: 'GRD002',
						name_grade: 'II',
						id_loan_type: 'LOAN0024',
						name_loan_type: 'Pendidikan ELP4',
						loan_plafond: 300000000,
					},
					{
						id_master_loan_plafond: 235,
						id_grade: 'GRD003',
						name_grade: 'III',
						id_loan_type: 'LOAN0024',
						name_loan_type: 'Pendidikan ELP4',
						loan_plafond: 300000000,
					},
					{
						id_master_loan_plafond: 236,
						id_grade: 'GRD004',
						name_grade: 'IV',
						id_loan_type: 'LOAN0024',
						name_loan_type: 'Pendidikan ELP4',
						loan_plafond: 300000000,
					},
					{
						id_master_loan_plafond: 237,
						id_grade: 'GRD005',
						name_grade: 'V',
						id_loan_type: 'LOAN0024',
						name_loan_type: 'Pendidikan ELP4',
						loan_plafond: 300000000,
					},
					{
						id_master_loan_plafond: 238,
						id_grade: 'GRD006',
						name_grade: 'VI',
						id_loan_type: 'LOAN0024',
						name_loan_type: 'Pendidikan ELP4',
						loan_plafond: 300000000,
					},
					{
						id_master_loan_plafond: 239,
						id_grade: 'GRD007',
						name_grade: 'VII',
						id_loan_type: 'LOAN0024',
						name_loan_type: 'Pendidikan ELP4',
						loan_plafond: 300000000,
					},
				],
			},
			{
				id_loan_type: 'LOAN0025',
				name_loan_type: 'Perjalanan Ibadah',
				icon_loan_type: '',
				min_plafond: 3048103.0,
				default_term: 9,
				interest: [
					{
						id_master_loan_interest: 211,
						id_loan_type: 'LOAN0025',
						name_loan_type: 'Perjalanan Ibadah',
						id_grade: 'GRD001',
						name_grade: 'I',
						interest: 6.5,
					},
					{
						id_master_loan_interest: 212,
						id_loan_type: 'LOAN0025',
						name_loan_type: 'Perjalanan Ibadah',
						id_grade: 'GRD002',
						name_grade: 'II',
						interest: 6.5,
					},
					{
						id_master_loan_interest: 213,
						id_loan_type: 'LOAN0025',
						name_loan_type: 'Perjalanan Ibadah',
						id_grade: 'GRD003',
						name_grade: 'III',
						interest: 6.5,
					},
					{
						id_master_loan_interest: 214,
						id_loan_type: 'LOAN0025',
						name_loan_type: 'Perjalanan Ibadah',
						id_grade: 'GRD004',
						name_grade: 'IV',
						interest: 6.5,
					},
					{
						id_master_loan_interest: 215,
						id_loan_type: 'LOAN0025',
						name_loan_type: 'Perjalanan Ibadah',
						id_grade: 'GRD005',
						name_grade: 'V',
						interest: 7.0,
					},
					{
						id_master_loan_interest: 216,
						id_loan_type: 'LOAN0025',
						name_loan_type: 'Perjalanan Ibadah',
						id_grade: 'GRD006',
						name_grade: 'VI',
						interest: 7.0,
					},
					{
						id_master_loan_interest: 217,
						id_loan_type: 'LOAN0025',
						name_loan_type: 'Perjalanan Ibadah',
						id_grade: 'GRD007',
						name_grade: 'VII',
						interest: 7.0,
					},
				],
				plafond: [
					{
						id_master_loan_plafond: 240,
						id_grade: 'GRD001',
						name_grade: 'I',
						id_loan_type: 'LOAN0025',
						name_loan_type: 'Perjalanan Ibadah',
						loan_plafond: 75000000,
					},
					{
						id_master_loan_plafond: 241,
						id_grade: 'GRD002',
						name_grade: 'II',
						id_loan_type: 'LOAN0025',
						name_loan_type: 'Perjalanan Ibadah',
						loan_plafond: 75000000,
					},
					{
						id_master_loan_plafond: 242,
						id_grade: 'GRD003',
						name_grade: 'III',
						id_loan_type: 'LOAN0025',
						name_loan_type: 'Perjalanan Ibadah',
						loan_plafond: 75000000,
					},
					{
						id_master_loan_plafond: 243,
						id_grade: 'GRD004',
						name_grade: 'IV',
						id_loan_type: 'LOAN0025',
						name_loan_type: 'Perjalanan Ibadah',
						loan_plafond: 75000000,
					},
					{
						id_master_loan_plafond: 244,
						id_grade: 'GRD005',
						name_grade: 'V',
						id_loan_type: 'LOAN0025',
						name_loan_type: 'Perjalanan Ibadah',
						loan_plafond: 150000000,
					},
					{
						id_master_loan_plafond: 245,
						id_grade: 'GRD006',
						name_grade: 'VI',
						id_loan_type: 'LOAN0025',
						name_loan_type: 'Perjalanan Ibadah',
						loan_plafond: 150000000,
					},
					{
						id_master_loan_plafond: 246,
						id_grade: 'GRD007',
						name_grade: 'VII',
						id_loan_type: 'LOAN0025',
						name_loan_type: 'Perjalanan Ibadah',
						loan_plafond: 150000000,
					},
				],
			},
			{
				id_loan_type: 'LOAN0026',
				name_loan_type: 'Pinjaman Rumah Idaman',
				icon_loan_type: '',
				min_plafond: 3048103.0,
				default_term: 9,
				interest: [
					{
						id_master_loan_interest: 218,
						id_loan_type: 'LOAN0026',
						name_loan_type: 'Pinjaman Rumah Idaman',
						id_grade: 'GRD001',
						name_grade: 'I',
						interest: 2.5,
					},
					{
						id_master_loan_interest: 219,
						id_loan_type: 'LOAN0026',
						name_loan_type: 'Pinjaman Rumah Idaman',
						id_grade: 'GRD002',
						name_grade: 'II',
						interest: 2.5,
					},
					{
						id_master_loan_interest: 220,
						id_loan_type: 'LOAN0026',
						name_loan_type: 'Pinjaman Rumah Idaman',
						id_grade: 'GRD003',
						name_grade: 'III',
						interest: 2.5,
					},
					{
						id_master_loan_interest: 221,
						id_loan_type: 'LOAN0026',
						name_loan_type: 'Pinjaman Rumah Idaman',
						id_grade: 'GRD004',
						name_grade: 'IV',
						interest: 3.0,
					},
				],
				plafond: [
					{
						id_master_loan_plafond: 247,
						id_grade: 'GRD001',
						name_grade: 'I',
						id_loan_type: 'LOAN0026',
						name_loan_type: 'Pinjaman Rumah Idaman',
						loan_plafond: 35000000,
					},
					{
						id_master_loan_plafond: 248,
						id_grade: 'GRD002',
						name_grade: 'II',
						id_loan_type: 'LOAN0026',
						name_loan_type: 'Pinjaman Rumah Idaman',
						loan_plafond: 35000000,
					},
					{
						id_master_loan_plafond: 249,
						id_grade: 'GRD003',
						name_grade: 'III',
						id_loan_type: 'LOAN0026',
						name_loan_type: 'Pinjaman Rumah Idaman',
						loan_plafond: 35000000,
					},
					{
						id_master_loan_plafond: 250,
						id_grade: 'GRD004',
						name_grade: 'IV',
						id_loan_type: 'LOAN0026',
						name_loan_type: 'Pinjaman Rumah Idaman',
						loan_plafond: 50000000,
					},
				],
			},
			{
				id_loan_type: 'LOAN0027',
				name_loan_type: 'RPB 2020',
				icon_loan_type: '',
				min_plafond: 3048103.0,
				default_term: 9,
				interest: [
					{
						id_master_loan_interest: 222,
						id_loan_type: 'LOAN0027',
						name_loan_type: 'RPB 2020',
						id_grade: 'GRD004',
						name_grade: 'IV',
						interest: 5.0,
					},
					{
						id_master_loan_interest: 223,
						id_loan_type: 'LOAN0027',
						name_loan_type: 'RPB 2020',
						id_grade: 'GRD005',
						name_grade: 'V',
						interest: 5.0,
					},
					{
						id_master_loan_interest: 224,
						id_loan_type: 'LOAN0027',
						name_loan_type: 'RPB 2020',
						id_grade: 'GRD006',
						name_grade: 'VI',
						interest: 5.0,
					},
					{
						id_master_loan_interest: 225,
						id_loan_type: 'LOAN0027',
						name_loan_type: 'RPB 2020',
						id_grade: 'GRD007',
						name_grade: 'VII',
						interest: 5.0,
					},
				],
				plafond: [
					{
						id_master_loan_plafond: 251,
						id_grade: 'GRD004',
						name_grade: 'IV',
						id_loan_type: 'LOAN0027',
						name_loan_type: 'RPB 2020',
						loan_plafond: 100000000,
					},
					{
						id_master_loan_plafond: 252,
						id_grade: 'GRD005',
						name_grade: 'V',
						id_loan_type: 'LOAN0027',
						name_loan_type: 'RPB 2020',
						loan_plafond: 100000000,
					},
					{
						id_master_loan_plafond: 253,
						id_grade: 'GRD006',
						name_grade: 'VI',
						id_loan_type: 'LOAN0027',
						name_loan_type: 'RPB 2020',
						loan_plafond: 100000000,
					},
					{
						id_master_loan_plafond: 254,
						id_grade: 'GRD007',
						name_grade: 'VII',
						id_loan_type: 'LOAN0027',
						name_loan_type: 'RPB 2020',
						loan_plafond: 100000000,
					},
				],
			},
		];

		this.dataGolongan = [
			{ id: 0, status: false, golongan: 'Not Set' },
			{ id: 1, status: false, golongan: 'I' },
			{ id: 2, status: false, golongan: 'II' },
			{ id: 3, status: false, golongan: 'III' },
			{ id: 4, status: false, golongan: 'IV' },
			{ id: 5, status: false, golongan: 'V' },
			{ id: 6, status: false, golongan: 'VI' },
			{ id: 7, status: false, golongan: 'VII' },
		];
	}
}
